import type { AttributeDefinition, VerticalId } from "./types.js";

const CONDITION = ["Naujas", "Naudotas", "Patenkinama"] as const;

export const VERTICAL_ATTRIBUTES: Record<VerticalId, readonly AttributeDefinition[]> = {
  TRANSPORT: [
    {
      key: "make",
      label: "Markė",
      type: "string",
      required: true,
      filterable: true,
      searchable: true,
      sortable: false,
    },
    {
      key: "model",
      label: "Modelis",
      type: "string",
      required: false,
      filterable: true,
      searchable: true,
      sortable: false,
    },
    {
      key: "year",
      label: "Metai",
      type: "number",
      required: false,
      filterable: true,
      searchable: false,
      sortable: true,
      min: 1950,
      max: 2100,
    },
    {
      key: "mileage",
      label: "Rida",
      type: "number",
      required: false,
      filterable: true,
      searchable: false,
      sortable: true,
      unit: "km",
      min: 0,
    },
    {
      key: "fuelType",
      label: "Kuro tipas",
      type: "enum",
      required: false,
      filterable: true,
      searchable: false,
      sortable: false,
      options: [
        "Benzinas",
        "Dyzelinas",
        "Elektra",
        "Hibridas",
        "Dujos",
      ],
    },
    {
      key: "transmission",
      label: "Transmisija",
      type: "enum",
      required: false,
      filterable: true,
      searchable: false,
      sortable: false,
      options: ["Mechaninė", "Automatinė"],
    },
    {
      key: "vin",
      label: "VIN",
      type: "string",
      required: false,
      filterable: false,
      searchable: true,
      sortable: false,
    },
  ],
  REAL_ESTATE: [
    {
      key: "propertyType",
      label: "Objekto tipas",
      type: "enum",
      required: true,
      filterable: true,
      searchable: true,
      sortable: false,
      options: ["Butas", "Namas", "Sklypas", "Komercija", "Sodas"],
    },
    {
      key: "area",
      label: "Plotas",
      type: "number",
      required: true,
      filterable: true,
      searchable: false,
      sortable: true,
      unit: "m²",
      min: 0.01,
    },
    {
      key: "rooms",
      label: "Kambarių skaičius",
      type: "number",
      required: false,
      filterable: true,
      searchable: false,
      sortable: true,
      min: 0,
    },
    {
      key: "yearBuilt",
      label: "Statybos metai",
      type: "number",
      required: false,
      filterable: true,
      searchable: false,
      sortable: true,
      min: 1800,
      max: 2100,
    },
    {
      key: "floor",
      label: "Aukštas",
      type: "number",
      required: false,
      filterable: true,
      searchable: false,
      sortable: true,
    },
    {
      key: "location",
      label: "Vieta",
      type: "location",
      required: true,
      filterable: true,
      searchable: true,
      sortable: false,
    },
  ],
  ELECTRONICS: [
    {
      key: "manufacturer",
      label: "Gamintojas",
      type: "string",
      required: true,
      filterable: true,
      searchable: true,
      sortable: false,
    },
    {
      key: "deviceModel",
      label: "Įrenginio versija",
      type: "string",
      required: false,
      filterable: true,
      searchable: true,
      sortable: false,
    },
    {
      key: "condition",
      label: "Būklė",
      type: "enum",
      required: true,
      filterable: true,
      searchable: false,
      sortable: false,
      options: CONDITION,
    },
    {
      key: "storage",
      label: "Atmintis",
      type: "enum",
      required: false,
      filterable: true,
      searchable: false,
      sortable: false,
      options: ["64 GB", "128 GB", "256 GB", "512 GB", "1 TB"],
    },
    {
      key: "warranty",
      label: "Prekės garantija",
      type: "enum",
      required: false,
      filterable: true,
      searchable: false,
      sortable: false,
      options: ["Yra", "Nėra"],
    },
  ],
  SERVICES: [
    {
      key: "serviceType",
      label: "Paslaugos tipas",
      type: "string",
      required: true,
      filterable: true,
      searchable: true,
      sortable: false,
    },
    {
      key: "serviceMode",
      label: "Lokacija / nuotoliu",
      type: "enum",
      required: false,
      filterable: true,
      searchable: false,
      sortable: false,
      options: ["Vietoje", "Nuotoliu", "Hibridas"],
    },
    {
      key: "pricingType",
      label: "Kainodaros tipas",
      type: "enum",
      required: true,
      filterable: true,
      searchable: false,
      sortable: false,
      options: ["Fiksuota", "Valandinis", "Sutartinis"],
    },
    {
      key: "duration",
      label: "Trukmė",
      type: "string",
      required: false,
      filterable: false,
      searchable: false,
      sortable: false,
    },
  ],
  JOBS: [
    {
      key: "jobTitle",
      label: "Pareigos",
      type: "string",
      required: true,
      filterable: true,
      searchable: true,
      sortable: false,
    },
    {
      key: "employmentType",
      label: "Darbo forma",
      type: "enum",
      required: true,
      filterable: true,
      searchable: false,
      sortable: false,
      options: ["Pilnas etatas", "Pusė etato", "Projektinis", "Praktika"],
    },
    {
      key: "salaryMin",
      label: "Atlygis nuo",
      type: "number",
      required: false,
      filterable: true,
      searchable: false,
      sortable: true,
      unit: "€",
      min: 0,
    },
    {
      key: "salaryMax",
      label: "Atlygis iki",
      type: "number",
      required: false,
      filterable: true,
      searchable: false,
      sortable: true,
      unit: "€",
      min: 0,
    },
    {
      key: "location",
      label: "Lokacija",
      type: "location",
      required: true,
      filterable: true,
      searchable: true,
      sortable: false,
    },
    {
      key: "workType",
      label: "Darbo tipas",
      type: "enum",
      required: false,
      filterable: true,
      searchable: false,
      sortable: false,
      options: ["Biure", "Nuotoliu", "Hibridas"],
    },
  ],
  HOME_GARDEN: [
    {
      key: "itemType",
      label: "Prekės / subkategorijos tipas",
      type: "enum",
      required: true,
      filterable: true,
      searchable: true,
      sortable: false,
      options: ["Baldai", "Sodo technika", "Įrankiai", "Dekoras", "Kita"],
    },
    {
      key: "condition",
      label: "Būklė",
      type: "enum",
      required: true,
      filterable: true,
      searchable: false,
      sortable: false,
      options: CONDITION,
    },
    {
      key: "material",
      label: "Medžiaga",
      type: "enum",
      required: false,
      filterable: true,
      searchable: false,
      sortable: false,
      options: ["Medis", "Metalas", "Plastikas", "Audinys", "Stiklas", "Kita"],
    },
    {
      key: "deliveryOption",
      label: "Pristatymo galimybė",
      type: "enum",
      required: false,
      filterable: true,
      searchable: false,
      sortable: false,
      options: ["Siunta", "Atsiėmimas", "Abu"],
    },
  ],
  CLOTHING: [
    {
      key: "clothingType",
      label: "Tipas",
      type: "string",
      required: true,
      filterable: true,
      searchable: true,
      sortable: false,
    },
    {
      key: "size",
      label: "Dydis",
      type: "enum",
      required: false,
      filterable: true,
      searchable: false,
      sortable: false,
      options: ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      key: "condition",
      label: "Būklė",
      type: "enum",
      required: true,
      filterable: true,
      searchable: false,
      sortable: false,
      options: CONDITION,
    },
  ],
  OTHER: [
    {
      key: "condition",
      label: "Būklė",
      type: "enum",
      required: true,
      filterable: true,
      searchable: false,
      sortable: false,
      options: CONDITION,
    },
  ],
};
