import type { AdaptiveCategoryConfig } from "./types";

const FASHION_GROUPS = [
  "Moterims",
  "Vyrams",
  "Vaikams",
  "Namams / Interjerui",
  "Augintiniams",
];

const FASHION_CONDITION_OPTS = [
  "Nauja su etiketėmis",
  "Nauja be etiketės",
  "Labai gera",
  "Gera",
  "Patenkinama",
];

const FASHION_SHIPPING = [
  "LP Express / Omniva terminalas",
  "Paštas",
  "Atsiėmimas gyvai",
];

export const ADAPTIVE_CATEGORIES: Record<
  AdaptiveCategoryConfig["key"],
  AdaptiveCategoryConfig
> = {
  vehicles: {
    key: "vehicles",
    label: "AUTOMOBILIŲ",
    portalStyle: "Auto",
    layout: "technical-grid",
    baseFields: ["title", "price", "location", "contact", "description"],
    fields: [
      { key: "make", label: "Markė", placeholder: "Volkswagen", critical: false, gridSpan: 1 },
      { key: "model", label: "Modelis", placeholder: "Golf", critical: false, gridSpan: 1 },
      { key: "year", label: "Metai", placeholder: "2015", critical: false, gridSpan: 1 },
      { key: "registrationMonth", label: "Mėnuo", placeholder: "03", critical: false, gridSpan: 1 },
      { key: "mileage", label: "Rida (km)", placeholder: "185 000 km", critical: true, gridSpan: 1 },
      { key: "engineCc", label: "Variklio tūris (cm³)", placeholder: "1598", critical: false, gridSpan: 1 },
      { key: "powerKw", label: "Galia (kW)", placeholder: "77", critical: false, gridSpan: 1 },
      { key: "powerHp", label: "Galia (AG)", placeholder: "105", critical: false, gridSpan: 1 },
      {
        key: "fuelType",
        label: "Kuro tipas",
        critical: true,
        inputType: "select",
        options: [
          "Benzinas",
          "Dyzelinas",
          "Elektra",
          "Benzinas / dujos",
          "Benzinas / elektra",
          "Dyzelinas / elektra",
          "Dujos",
        ],
        gridSpan: 1,
      },
      {
        key: "gearbox",
        label: "Pavarų dėžė",
        critical: true,
        inputType: "select",
        options: ["Mechaninė", "Automatinė"],
        gridSpan: 1,
      },
      {
        key: "bodyType",
        label: "Kėbulo tipas",
        critical: true,
        inputType: "select",
        options: [
          "Sedanas",
          "Hečbekas",
          "Universalas",
          "Visureigis / SUV",
          "Vienatūris",
          "Kupė (Coupe)",
          "Kabrioletas",
          "Pikapas",
          "Komercinis",
        ],
        gridSpan: 1,
      },
      {
        key: "steering",
        label: "Vairas",
        inputType: "select",
        options: ["Kairėje", "Dešinėje"],
        gridSpan: 1,
      },
      {
        key: "driveType",
        label: "Varomieji ratai",
        inputType: "select",
        options: [
          "Priekiniai (FWD)",
          "Galiniai (RWD)",
          "Visi varantys (AWD / 4x4)",
        ],
        gridSpan: 1,
      },
      {
        key: "defects",
        label: "Defektai",
        critical: true,
        inputType: "select",
        options: [
          "Be defektų",
          "Daužtas",
          "Su variklio defektu",
          "Su pavarų dėžės defektu",
          "Kitas defektas",
        ],
        gridSpan: 1,
      },
      {
        key: "vehicleOptions",
        label: "Papildomos opcijos",
        inputType: "checklist",
        options: [
          "Kondicionierius / Klimato kontrolė",
          "Odinis salonas",
          "Panoraminis stogas",
          "LED / Xenon žibintai",
          "Navigacija / GPS",
          "Atstumo jutikliai",
          "Atbulinės eigos kamera",
          "Kruizo kontrolė (Autopilotas)",
          "Šildomos sėdynės",
          "Lengvojo lydinio ratlankiai",
        ],
        gridSpan: 2,
      },
      { key: "taExpiry", label: "Techninė apžiūra iki", placeholder: "2027-03", critical: false, gridSpan: 1 },
      { key: "sdkCode", label: "SDK kodas", placeholder: "SDK-123456", critical: false, gridSpan: 1 },
      {
        key: "vin",
        label: "VIN kėbulo numeris",
        placeholder: "WVWZZZ1KZAW123456",
        critical: false,
        gridSpan: 2,
      },
    ],
  },
  clothing: {
    key: "clothing",
    label: "APRANGA",
    portalStyle: "Apranga",
    layout: "tag-social",
    baseFields: ["title", "price", "location", "contact", "description"],
    fields: [
      {
        key: "clothingType",
        label: "Pagrindinė grupė / Tipas",
        critical: true,
        inputType: "select",
        options: FASHION_GROUPS,
      },
      {
        key: "fashionSubcategory",
        label: "Subkategorija",
        critical: true,
        placeholder: "Striukės, Suknelės, Sportbačiai…",
      },
      {
        key: "size",
        label: "Dydis",
        critical: true,
        placeholder: "S / 40 / 104 cm",
      },
      { key: "brand", label: "Prekės ženklas", placeholder: "Zara, Nike…", critical: true },
      {
        key: "condition",
        label: "Būklė",
        critical: true,
        inputType: "select",
        options: FASHION_CONDITION_OPTS,
      },
      {
        key: "colors",
        label: "Spalva",
        critical: true,
        inputType: "checklist",
        options: [
          "Juoda",
          "Balta",
          "Pilka",
          "Mėlyna",
          "Raudona",
          "Rožinė",
          "Žalia",
          "Ruda",
          "Daugiaspalvė",
        ],
      },
      {
        key: "shippingOptions",
        label: "Siuntimo parinktys",
        inputType: "checklist",
        options: FASHION_SHIPPING,
      },
    ],
  },
  services: {
    key: "services",
    label: "PASLAUGŲ",
    portalStyle: "Paslaugos",
    layout: "service-profile",
    baseFields: ["title", "price", "location", "contact", "description"],
    fields: [
      { key: "experience", label: "Patirtis", placeholder: "8 m. patirtis", critical: true },
      {
        key: "serviceList",
        label: "Darbų sąrašas",
        critical: true,
        inputType: "checklist",
        options: [
          "Montavimas",
          "Remontas",
          "Konsultacija",
          "Diagnostika",
          "Valymas",
          "Transportas",
        ],
      },
      {
        key: "invoicing",
        label: "Sąskaitos",
        inputType: "select",
        options: ["Taip, su PVM", "Taip, be PVM", "Ne"],
        critical: true,
      },
      {
        key: "workingRadius",
        label: "Atstumas kur vyksta",
        placeholder: "Vilnius / Kaunas / Lietuva + 30 km",
        critical: true,
      },
    ],
  },
  jobs: {
    key: "jobs",
    label: "CVBANKAS",
    portalStyle: "Darbas",
    layout: "service-profile",
    baseFields: ["title", "price", "location", "contact", "description"],
    fields: [
      {
        key: "jobType",
        label: "Srautas",
        critical: true,
        inputType: "select",
        options: ["Siūlau darbą", "Ieškau darbo"],
      },
      { key: "employerName", label: "Įmonės pavadinimas", placeholder: "UAB Pavadinimas" },
      { key: "companyCode", label: "Juridinis kodas", placeholder: "123456789" },
      { key: "companyLogo", label: "Logotipas (URL)", placeholder: "https://…" },
      { key: "jobTitle", label: "Pareigų pavadinimas / Vakansija", critical: true },
      {
        key: "experienceArea",
        label: "Pareigų sritis",
        critical: true,
        inputType: "select",
        options: [
          "IT",
          "Pardavimai",
          "Transportas",
          "Finansai",
          "Gamyba",
          "Klientų aptarnavimas",
          "Administravimas",
          "Sveikata",
          "Kita",
        ],
      },
      {
        key: "education",
        label: "Išsilavinimas",
        inputType: "select",
        options: [
          "Vidurinis",
          "Profesinis",
          "Aukštasis koleginis",
          "Aukštasis universitetinis",
        ],
      },
      {
        key: "employmentType",
        label: "Darbo pobūdis / Grafikas",
        critical: true,
        inputType: "select",
        options: [
          "Pilnas etatas",
          "Pusė etato",
          "Projektinis",
          "Praktika",
          "Pamaininis darbas",
        ],
      },
      {
        key: "locationType",
        label: "Darbo vieta",
        critical: true,
        inputType: "select",
        options: ["Nuotolinis", "Ofise", "Hibridinis"],
      },
      { key: "salaryFrom", label: "Atlyginimas nuo", placeholder: "1500" },
      { key: "salaryTo", label: "Atlyginimas iki", placeholder: "2500" },
      {
        key: "salaryGrossNet",
        label: "Bruto / Neto",
        inputType: "select",
        options: ["Bruto", "Neto"],
      },
      {
        key: "experienceRequired",
        label: "Reikalaujama patirtis",
        inputType: "select",
        options: ["Nereikia", "1-2 metai", "3-5 metai", "5+ metų"],
      },
      {
        key: "languages",
        label: "Kalbos",
        inputType: "checklist",
        options: ["Lietuvių", "Anglų", "Rusų", "Vokiečių"],
      },
      {
        key: "languageLevel",
        label: "Kalbos lygis",
        inputType: "select",
        options: ["A1", "A2", "B1", "B2", "C1", "C2"],
      },
      { key: "cvFile", label: "CV failas (PDF/Word URL)", placeholder: "https://…" },
      { key: "cvEmail", label: "CV el. paštas", placeholder: "cv@email.lt" },
      { key: "companyOffers", label: "Įmonė siūlo", inputType: "textarea", gridSpan: 2 },
      { key: "requirements", label: "Reikalavimai kandidatui", inputType: "textarea", gridSpan: 2 },
      { key: "competencies", label: "Kompetencijos / Programos", placeholder: "Excel, SAP…", gridSpan: 2 },
    ],
  },
  real_estate: {
    key: "real_estate",
    label: "ARUODAS.LT",
    portalStyle: "NT",
    layout: "estate-sheet",
    baseFields: ["title", "price", "location", "contact", "description"],
    fields: [
      {
        key: "propertyType",
        label: "Objekto tipas",
        critical: true,
        inputType: "select",
        options: [
          "Butas",
          "Namas",
          "Sodyba",
          "Sodo namelis",
          "Žemės sklypas",
          "Miško sklypas",
          "Patalpos / Komercija",
          "Garažas",
        ],
      },
      {
        key: "transactionType",
        label: "Sandorio tipas",
        critical: true,
        inputType: "select",
        options: ["Parduoda", "Nuomoja", "Trumpalaikė nuoma"],
      },
      { key: "area", label: "Plotas (m²)", placeholder: "62", critical: true, gridSpan: 1 },
      { key: "landArea", label: "Sklypo plotas (a / ha)", placeholder: "12 a", gridSpan: 1 },
      {
        key: "landPurpose",
        label: "Sklypo paskirtis",
        inputType: "select",
        options: [
          "Namų valda",
          "Žemės ūkio",
          "Komercinė",
          "Miškų ūkio",
          "Sodų",
          "Rekreacinė",
        ],
        gridSpan: 1,
      },
      {
        key: "landUtilities",
        label: "Komunikacijos",
        inputType: "checklist",
        options: ["Elektra", "Dujos", "Vandentiekis"],
        gridSpan: 1,
      },
      {
        key: "rooms",
        label: "Kambarių skaičius",
        critical: true,
        inputType: "select",
        options: ["1", "2", "3", "4", "5+"],
        gridSpan: 1,
      },
      { key: "floor", label: "Aukštas", placeholder: "2", gridSpan: 1 },
      { key: "floors", label: "Aukštų skaičius pastate", placeholder: "5", gridSpan: 1 },
      { key: "buildYear", label: "Statybos metai", placeholder: "2015", gridSpan: 1 },
      {
        key: "furnishing",
        label: "Įrengimas",
        inputType: "select",
        options: ["Įrengtas", "Dalinė apdaila", "Neįrengtas", "Remontuotinas"],
        critical: true,
        gridSpan: 1,
      },
      {
        key: "heating",
        label: "Šildymo tipas",
        inputType: "select",
        options: [
          "Centrinis",
          "Autonominis/Dujinis",
          "Aeroterminis/Geoterminis",
          "Kietu kuru",
        ],
        critical: true,
        gridSpan: 1,
      },
      {
        key: "ntFeatures",
        label: "Papildomos opcijos",
        inputType: "checklist",
        options: [
          "Balkonas / Terasa",
          "Sandėliukas",
          "Parkavimo vieta",
          "Aptverta teritorija",
          "Parduodama su baldais",
        ],
        gridSpan: 2,
      },
    ],
  },
  universal: {
    key: "universal",
    label: "SKELBIU.LT",
    portalStyle: "Prekės",
    layout: "universal",
    baseFields: ["title", "price", "location", "contact", "description"],
    fields: [
      { key: "skelbiuCategory", label: "Kategorija", critical: true, placeholder: "Elektronika › Telefonai" },
      {
        key: "manufacturer",
        label: "Gamintojas",
        inputType: "select",
        options: ["Apple", "Samsung", "Sony", "Huawei", "Xiaomi", "LG", "Kita"],
      },
      { key: "deviceModel", label: "Modelis", placeholder: "iPhone 15 Pro" },
      {
        key: "storageCapacity",
        label: "Atminties talpa",
        inputType: "select",
        options: ["32 GB", "64 GB", "128 GB", "256 GB", "512 GB", "1 TB", "2 TB+"],
      },
      {
        key: "deviceOs",
        label: "Operacinė sistema",
        inputType: "select",
        options: ["iOS", "Android", "Windows", "macOS", "Linux", "Kita"],
      },
      {
        key: "warranty",
        label: "Garantija",
        inputType: "select",
        options: ["Yra", "Nėra"],
      },
      {
        key: "furnitureType",
        label: "Baldų tipas",
        inputType: "select",
        options: ["Minkšti baldai", "Lovos", "Stalai", "Spintos", "Kėdės", "Kita"],
      },
      {
        key: "material",
        label: "Medžiaga",
        inputType: "select",
        options: ["Medis", "Metalas", "Plastikas", "Oda / Audinys", "Stiklas", "Kita"],
      },
      {
        key: "toolType",
        label: "Įrankio / medžiagos tipas",
        inputType: "select",
        options: [
          "Elektriniai įrankiai",
          "Sodo technika",
          "Statybinės medžiagos",
          "Rankiniai įrankiai",
        ],
      },
      {
        key: "powerSource",
        label: "Maitinimo būdas",
        inputType: "select",
        options: ["Akumuliatorinis", "Laidinis", "Benzininis", "Kita"],
      },
      {
        key: "condition",
        label: "Būklė",
        inputType: "select",
        options: ["Naujas", "Naudotas"],
        critical: true,
      },
    ],
  },
};

export function getAdaptiveConfig(key: AdaptiveCategoryConfig["key"]) {
  return ADAPTIVE_CATEGORIES[key];
}
