import type { AdaptiveCategoryConfig } from "./types";

export const ADAPTIVE_CATEGORIES: Record<
  AdaptiveCategoryConfig["key"],
  AdaptiveCategoryConfig
> = {
  vehicles: {
    key: "vehicles",
    label: "AUTOMOBILIŲ",
    portalStyle: "Auto",
    layout: "technical-grid",
    baseFields: ["title", "price", "location", "contact", "description"],
    fields: [
      { key: "make", label: "Markė", placeholder: "Volkswagen", critical: false, gridSpan: 1 },
      { key: "model", label: "Modelis", placeholder: "Golf", critical: false, gridSpan: 1 },
      { key: "year", label: "Metai", placeholder: "2015", critical: false, gridSpan: 1 },
      { key: "mileage", label: "Rida (km)", placeholder: "185 000 km", critical: true, gridSpan: 1 },
      { key: "engineCc", label: "Variklio tūris (l)", placeholder: "1.6", critical: false, gridSpan: 1 },
      { key: "powerKw", label: "Galia (kW)", placeholder: "77", critical: false, gridSpan: 1 },
      {
        key: "fuelType",
        label: "Kuro tipas",
        placeholder: "Dyzelinas",
        critical: true,
        inputType: "select",
        options: [
          "Dyzelinas",
          "Benzinas",
          "Elektra",
          "Benzinas / dujos",
          "Benzinas / elektra",
          "Hibridas",
        ],
        gridSpan: 1,
      },
      {
        key: "bodyType",
        label: "Kėbulo tipas",
        placeholder: "Hečbekas",
        critical: true,
        inputType: "select",
        options: [
          "Sedanas",
          "Universalas",
          "Hečbekas",
          "Visureigis",
          "Vienatūris",
          "Kupė",
        ],
        gridSpan: 1,
      },
      {
        key: "gearbox",
        label: "Pavarų dėžė",
        critical: true,
        inputType: "select",
        options: ["Automatinė", "Mechaninė"],
        gridSpan: 1,
      },
      {
        key: "driveType",
        label: "Varantieji ratai",
        inputType: "select",
        options: ["Priekiniai", "Galiniai", "Visi varantieji"],
        gridSpan: 1,
      },
      { key: "taExpiry", label: "TA galioja iki", placeholder: "2027-03", critical: false, gridSpan: 1 },
      { key: "defects", label: "Defektai", placeholder: "Nėra / smulkūs įbrėžimai", gridSpan: 2 },
      {
        key: "vin",
        label: "VIN kėbulo numeris",
        placeholder: "WVWZZZ1KZAW123456",
        critical: false,
        gridSpan: 2,
      },
    ],
  },
  clothing: {
    key: "clothing",
    label: "APRANGOS",
    portalStyle: "Apranga",
    layout: "tag-social",
    baseFields: ["title", "price", "location", "contact", "description"],
    fields: [
      {
        key: "clothingType",
        label: "Tipas",
        critical: true,
        inputType: "select",
        options: ["Moterims", "Vyrams", "Vaikams"],
      },
      {
        key: "size",
        label: "Dydis",
        placeholder: "M / 38 / 42",
        critical: true,
        inputType: "select",
        options: ["XS", "S", "M", "L", "XL", "XXL"],
      },
      { key: "brand", label: "Prekės ženklas", placeholder: "Zara, Nike…", critical: true },
      {
        key: "condition",
        label: "Būklė",
        critical: true,
        inputType: "select",
        options: [
          "Nauja su etiketėmis",
          "Nauja be etiketės",
          "Labai gera",
          "Gera",
          "Patenkinama",
        ],
      },
      { key: "color", label: "Spalva", placeholder: "Juoda, mėlyna…", critical: true },
    ],
  },
  services: {
    key: "services",
    label: "PASLAUGŲ",
    portalStyle: "Paslaugos",
    layout: "service-profile",
    baseFields: ["title", "price", "location", "contact", "description"],
    fields: [
      { key: "experience", label: "Patirtis", placeholder: "8 m. patirtis", critical: true },
      {
        key: "serviceList",
        label: "Darbų sąrašas",
        critical: true,
        inputType: "checklist",
        options: [
          "Montavimas",
          "Remontas",
          "Konsultacija",
          "Diagnostika",
          "Valymas",
          "Transportas",
        ],
      },
      {
        key: "invoicing",
        label: "Sąskaitos",
        inputType: "select",
        options: ["Taip, su PVM", "Taip, be PVM", "Ne"],
        critical: true,
      },
      {
        key: "workingRadius",
        label: "Atstumas kur vyksta",
        placeholder: "Vilnius / Kaunas / Lietuva + 30 km",
        critical: true,
      },
    ],
  },
  jobs: {
    key: "jobs",
    label: "DARBO",
    portalStyle: "Darbas",
    layout: "service-profile",
    baseFields: ["title", "price", "location", "contact", "description"],
    fields: [
      {
        key: "jobType",
        label: "Skelbimo tipas",
        critical: true,
        inputType: "select",
        options: ["Siūlau darbą", "Ieškau darbo"],
      },
      { key: "employerName", label: "Įmonės pavadinimas", placeholder: "UAB Pavadinimas", critical: false },
      { key: "jobTitle", label: "Siūloma pozicija / pareigos", critical: true },
      {
        key: "employmentType",
        label: "Darbo pobūdis",
        critical: true,
        inputType: "select",
        options: ["Pilnas etatas", "Pusė etato", "Projektinis", "Praktika"],
      },
      {
        key: "locationType",
        label: "Darbo vieta",
        critical: true,
        inputType: "select",
        options: ["Nuotolinis", "Ofise", "Hibridinis"],
      },
      { key: "salaryFrom", label: "Atlyginimas nuo", placeholder: "1500", critical: false },
      { key: "salaryTo", label: "Atlyginimas iki", placeholder: "2500", critical: false },
      {
        key: "salaryGrossNet",
        label: "Atlyginimo tipas",
        inputType: "select",
        options: ["Bruto", "Neto"],
      },
      {
        key: "experienceRequired",
        label: "Reikalaujama patirtis",
        inputType: "select",
        options: ["Nereikia", "1-3 metai", "3-5 metai", "5+ metų"],
      },
      {
        key: "languages",
        label: "Reikalaujamos kalbos",
        inputType: "checklist",
        options: ["Lietuvių", "Anglų", "Rusų"],
      },
      { key: "cvEmail", label: "CV / profilis (ieškantiems)", placeholder: "cv@email.lt", critical: false },
      {
        key: "experienceArea",
        label: "Pageidaujama sritis (ieškantiems)",
        inputType: "select",
        options: ["IT", "Pardavimai", "Administravimas", "Gamyba", "Sveikata", "Kita"],
      },
    ],
  },
  real_estate: {
    key: "real_estate",
    label: "NEKILNOJAMOJO TURTO",
    portalStyle: "NT",
    layout: "estate-sheet",
    baseFields: ["title", "price", "location", "contact", "description"],
    fields: [
      {
        key: "transactionType",
        label: "Sandorio tipas",
        critical: true,
        inputType: "select",
        options: ["Parduoda", "Nuomoja", "Trumpalaikė nuoma"],
      },
      {
        key: "propertyType",
        label: "Objekto tipas",
        critical: true,
        inputType: "select",
        options: ["Butas", "Namas", "Sklypas", "Patalpos"],
      },
      { key: "area", label: "Plotas (m²)", placeholder: "62", critical: true, gridSpan: 1 },
      {
        key: "rooms",
        label: "Kambarių skaičius",
        placeholder: "3",
        critical: true,
        inputType: "select",
        options: ["1", "2", "3", "4", "5+"],
        gridSpan: 1,
      },
      {
        key: "furnishing",
        label: "Įrengimas",
        inputType: "select",
        options: ["Įrengtas", "Dalinė apdaila", "Neįrengtas", "Remontuotinas"],
        critical: true,
        gridSpan: 1,
      },
      {
        key: "heating",
        label: "Šildymo tipas",
        inputType: "select",
        options: ["Centrinis", "Autonominis/Dujinis", "Aeroterminis", "Kietu kuru"],
        critical: true,
        gridSpan: 1,
      },
      { key: "floor", label: "Aukštas", placeholder: "2", critical: false, gridSpan: 1 },
      { key: "floors", label: "Aukštų skaičius pastate", placeholder: "5", critical: false, gridSpan: 1 },
    ],
  },
  universal: {
    key: "universal",
    label: "BENDRAS",
    portalStyle: "Prekės",
    layout: "universal",
    baseFields: ["title", "price", "location", "contact", "description"],
    fields: [],
  },
};

export function getAdaptiveConfig(key: AdaptiveCategoryConfig["key"]) {
  return ADAPTIVE_CATEGORIES[key];
}
