/** Auto-generated by scripts/generate-mock-catalog.mjs — do not edit manually */
import type { DemoListingRow } from "./demo-listings.js";

export const GENERATED_DEMO_LISTINGS: DemoListingRow[] = [
  {
    "id": "lt-auto-001",
    "seller_id": "seller-auto-1",
    "title": "BMW 320d 2003",
    "price": 4250,
    "location": "Kaunas",
    "distance_km": 1,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "bmw",
      "320d",
      "automobilis",
      "dyzelinas",
      "kaunas"
    ],
    "has_video": false,
    "contact": "Tel. +370 61000000",
    "description": "BMW 320d 2003 m. iš Kaunas. Rida 220 898 km, dyzelinas, mechaninė. Kėbulo būklė puiki, keli kosmetiniai pabraižymai. Techninė apžiūra galioja iki 2025-01. Be dūmų, be rūdžių. Parkavimo jutikliai priekyje ir gale. Serviso knygelė su visais įrašais.",
    "attributes": {
      "make": "BMW",
      "model": "320d",
      "year": "2003",
      "mileage": "220 898 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Sedanas",
      "transmission": "Mechaninė",
      "taExpiry": "2025-01",
      "vin": "WBA0YWUSPMKHFDB97",
      "defects": "Smulkūs kosmetiniai defektai"
    },
    "provider_verified": true,
    "vin_verified": false
  },
  {
    "id": "lt-auto-002",
    "seller_id": "seller-auto-2",
    "title": "BMW 320d Touring 2010",
    "price": 15000,
    "location": "Panevėžys",
    "distance_km": 2.3,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "bmw",
      "320d",
      "automobilis",
      "dyzelinas",
      "panevėžys"
    ],
    "has_video": false,
    "contact": "Tel. +370 61007919",
    "description": "BMW 320d Touring 2010 m. iš Panevėžys. Rida 142 985 km, dyzelinas, automatinė. Be eismo įvykių, originali dažų spalva. Serviso knygelė su visais įrašais. Vienas savininkas Lietuvoje. Automatinis parkavimas. Du raktelių komplektas.",
    "attributes": {
      "make": "BMW",
      "model": "320d Touring",
      "year": "2010",
      "mileage": "142 985 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Universalas",
      "transmission": "Automatinė",
      "taExpiry": "2026-02",
      "vin": "WBAHFDB97531ZXVTR",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-003",
    "seller_id": "seller-auto-3",
    "title": "BMW 520d 2017",
    "price": 22000,
    "location": "Mažeikiai",
    "distance_km": 3.6,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "bmw",
      "520d",
      "automobilis",
      "dyzelinas",
      "mažeikiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 61015838",
    "description": "BMW 520d 2017 m. iš Mažeikiai. Rida 103 574 km, dyzelinas, automatinė su padėtimis. Priekinis buferis dažytas, techniškai tvarkinga. Du raktelių komplektas. Importuota iš Vokietijos, tvarkinga istorija. Xenon/LED priekiniai žibintai. Naujos vasarinės padangos.",
    "attributes": {
      "make": "BMW",
      "model": "520d",
      "year": "2017",
      "mileage": "103 574 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Sedanas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2025-03",
      "vin": "WBA1ZXVTRNLJGECA8",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-004",
    "seller_id": "seller-auto-4",
    "title": "BMW 530e 2024",
    "price": 29150,
    "location": "Kupiškis",
    "distance_km": 4.9,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "bmw",
      "530e",
      "automobilis",
      "plug-in hibridas",
      "kupiškis"
    ],
    "has_video": false,
    "contact": "Tel. +370 61023757",
    "description": "BMW 530e 2024 m. iš Kupiškis. Rida 22 665 km, plug-in hibridas, mechaninė. Salonas labai tvarkingas, nerūkytas. Naujos vasarinės padangos. Neseniai atlikta didžioji TO. Start-stop sistema, mažos sąnaudos. Klimato kontrolė, šildomos sėdynės.",
    "attributes": {
      "make": "BMW",
      "model": "530e",
      "year": "2024",
      "mileage": "22 665 km",
      "fuelType": "Plug-in hibridas",
      "bodyType": "Sedanas",
      "transmission": "Mechaninė",
      "taExpiry": "2026-04",
      "vin": "WBAJGECA86420YWUS",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": false
  },
  {
    "id": "lt-auto-005",
    "seller_id": "seller-auto-5",
    "title": "BMW X5 xDrive30d 2006",
    "price": 7400,
    "location": "Ukmergė",
    "distance_km": 6.2,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "bmw",
      "x5",
      "automobilis",
      "dyzelinas",
      "ukmergė"
    ],
    "has_video": false,
    "contact": "Tel. +370 61031676",
    "description": "BMW X5 xDrive30d 2006 m. iš Ukmergė. Rida 245 793 km, dyzelinas, automatinė. Visi saugumo elementai veikia, paruošta registracijai. Klimato kontrolė, šildomos sėdynės. Nauja vairo traukė, stabdžių diskai. 4×4 visų ratų pavara. Navigacija, atbulinės kameros.",
    "attributes": {
      "make": "BMW",
      "model": "X5 xDrive30d",
      "year": "2006",
      "mileage": "245 793 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Visureigis",
      "transmission": "Automatinė",
      "taExpiry": "2025-05",
      "vin": "WBA20YWUSPMKHFDB9",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-006",
    "seller_id": "seller-auto-6",
    "title": "BMW 318i 2013",
    "price": 17750,
    "location": "Kėdainiai",
    "distance_km": 7.5,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "bmw",
      "318i",
      "automobilis",
      "benzinas",
      "kėdainiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 61039595",
    "description": "BMW 318i 2013 m. iš Kėdainiai. Rida 147 238 km, benzinas, automatinė su padėtimis. Kėbulo būklė puiki, keli kosmetiniai pabraižymai. Navigacija, atbulinės kameros. Odinis salonas, panoraminis stogas. Automatinė bagažinės dangtis. LED žibintai, lietaus jutiklis.",
    "attributes": {
      "make": "BMW",
      "model": "318i",
      "year": "2013",
      "mileage": "147 238 km",
      "fuelType": "Benzinas",
      "bodyType": "Sedanas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2026-06",
      "vin": "WBAKHFDB97531ZXVT",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-007",
    "seller_id": "seller-auto-7",
    "title": "Audi A4 Avant 2020",
    "price": 23950,
    "location": "Pasvalys",
    "distance_km": 8.8,
    "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "audi",
      "a4",
      "automobilis",
      "dyzelinas",
      "pasvalys"
    ],
    "has_video": false,
    "contact": "Tel. +370 61047514",
    "description": "Audi A4 Avant 2020 m. iš Pasvalys. Rida 80 465 km, dyzelinas, mechaninė. Be eismo įvykių, originali dažų spalva. LED žibintai, lietaus jutiklis. Apple CarPlay / Android Auto. Techninė apžiūra galioja iki 2025-07. Be dūmų, be rūdžių.",
    "attributes": {
      "make": "Audi",
      "model": "A4 Avant",
      "year": "2020",
      "mileage": "80 465 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Universalas",
      "transmission": "Mechaninė",
      "taExpiry": "2025-07",
      "vin": "WBA31ZXVTRNLJGECA",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": false
  },
  {
    "id": "lt-auto-008",
    "seller_id": "seller-auto-8",
    "title": "Audi A4 2002",
    "price": 5550,
    "location": "Visaginas",
    "distance_km": 10.1,
    "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "audi",
      "a4",
      "automobilis",
      "dyzelinas",
      "visaginas"
    ],
    "has_video": false,
    "contact": "Tel. +370 61055433",
    "description": "Audi A4 2002 m. iš Visaginas. Rida 254 249 km, dyzelinas, automatinė. Priekinis buferis dažytas, techniškai tvarkinga. Be dūmų, be rūdžių. Parkavimo jutikliai priekyje ir gale. Serviso knygelė su visais įrašais. Vienas savininkas Lietuvoje.",
    "attributes": {
      "make": "Audi",
      "model": "A4",
      "year": "2002",
      "mileage": "254 249 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Sedanas",
      "transmission": "Automatinė",
      "taExpiry": "2026-08",
      "vin": "WBALJGECA86420YWU",
      "defects": "Nėra"
    },
    "provider_verified": true,
    "vin_verified": true
  },
  {
    "id": "lt-auto-009",
    "seller_id": "seller-auto-9",
    "title": "Audi A6 2009",
    "price": 12550,
    "location": "Kaunas",
    "distance_km": 11.4,
    "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "audi",
      "a6",
      "automobilis",
      "dyzelinas",
      "kaunas"
    ],
    "has_video": false,
    "contact": "Tel. +370 61063352",
    "description": "Audi A6 2009 m. iš Kaunas. Rida 171 550 km, dyzelinas, automatinė su padėtimis. Salonas labai tvarkingas, nerūkytas. Vienas savininkas Lietuvoje. Automatinis parkavimas. Du raktelių komplektas. Importuota iš Vokietijos, tvarkinga istorija.",
    "attributes": {
      "make": "Audi",
      "model": "A6",
      "year": "2009",
      "mileage": "171 550 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Sedanas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2025-09",
      "vin": "WBA420YWUSPMKHFDB",
      "defects": "Smulkūs kosmetiniai defektai"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-010",
    "seller_id": "seller-auto-10",
    "title": "Audi Q5 2016",
    "price": 19900,
    "location": "Panevėžys",
    "distance_km": 12.7,
    "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "audi",
      "q5",
      "automobilis",
      "dyzelinas",
      "panevėžys"
    ],
    "has_video": false,
    "contact": "Tel. +370 61071271",
    "description": "Audi Q5 2016 m. iš Panevėžys. Rida 87 353 km, dyzelinas, mechaninė. Visi saugumo elementai veikia, paruošta registracijai. Importuota iš Vokietijos, tvarkinga istorija. Xenon/LED priekiniai žibintai. Naujos vasarinės padangos. Neseniai atlikta didžioji TO.",
    "attributes": {
      "make": "Audi",
      "model": "Q5",
      "year": "2016",
      "mileage": "87 353 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Visureigis",
      "transmission": "Mechaninė",
      "taExpiry": "2026-10",
      "vin": "WBAMKHFDB97531ZXV",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": false
  },
  {
    "id": "lt-auto-011",
    "seller_id": "seller-auto-11",
    "title": "Audi A3 Sportback 2023",
    "price": 26700,
    "location": "Mažeikiai",
    "distance_km": 11,
    "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "audi",
      "a3",
      "automobilis",
      "benzinas",
      "mažeikiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 61079190",
    "description": "Audi A3 Sportback 2023 m. iš Mažeikiai. Rida 41 658 km, benzinas, automatinė. Kėbulo būklė puiki, keli kosmetiniai pabraižymai. Neseniai atlikta didžioji TO. Start-stop sistema, mažos sąnaudos. Klimato kontrolė, šildomos sėdynės. Nauja vairo traukė, stabdžių diskai.",
    "attributes": {
      "make": "Audi",
      "model": "A3 Sportback",
      "year": "2023",
      "mileage": "41 658 km",
      "fuelType": "Benzinas",
      "bodyType": "Hečbekas",
      "transmission": "Automatinė",
      "taExpiry": "2025-11",
      "vin": "WBA531ZXVTRNLJGEC",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-012",
    "seller_id": "seller-auto-12",
    "title": "Volkswagen Golf 2005",
    "price": 8200,
    "location": "Kupiškis",
    "distance_km": 12.3,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volkswagen",
      "golf",
      "automobilis",
      "dyzelinas",
      "kupiškis"
    ],
    "has_video": false,
    "contact": "Tel. +370 61087109",
    "description": "Volkswagen Golf 2005 m. iš Kupiškis. Rida 184 950 km, dyzelinas, automatinė su padėtimis. Be eismo įvykių, originali dažų spalva. Nauja vairo traukė, stabdžių diskai. 4×4 visų ratų pavara. Navigacija, atbulinės kameros. Odinis salonas, panoraminis stogas.",
    "attributes": {
      "make": "Volkswagen",
      "model": "Golf",
      "year": "2005",
      "mileage": "184 950 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Hečbekas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2026-12",
      "vin": "WBANLJGECA86420YW",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-013",
    "seller_id": "seller-auto-1",
    "title": "Volkswagen Passat 2012",
    "price": 15250,
    "location": "Ukmergė",
    "distance_km": 13.6,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volkswagen",
      "passat",
      "automobilis",
      "dyzelinas",
      "ukmergė"
    ],
    "has_video": false,
    "contact": "Tel. +370 61095028",
    "description": "Volkswagen Passat 2012 m. iš Ukmergė. Rida 116 609 km, dyzelinas, mechaninė. Priekinis buferis dažytas, techniškai tvarkinga. Odinis salonas, panoraminis stogas. Automatinė bagažinės dangtis. LED žibintai, lietaus jutiklis. Apple CarPlay / Android Auto.",
    "attributes": {
      "make": "Volkswagen",
      "model": "Passat",
      "year": "2012",
      "mileage": "116 609 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Universalas",
      "transmission": "Mechaninė",
      "taExpiry": "2025-01",
      "vin": "WBA6420YWUSPMKHFD",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": false
  },
  {
    "id": "lt-auto-014",
    "seller_id": "seller-auto-2",
    "title": "Volkswagen Tiguan 2019",
    "price": 22650,
    "location": "Kėdainiai",
    "distance_km": 14.9,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volkswagen",
      "tiguan",
      "automobilis",
      "dyzelinas",
      "kėdainiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 61102947",
    "description": "Volkswagen Tiguan 2019 m. iš Kėdainiai. Rida 46 770 km, dyzelinas, automatinė. Salonas labai tvarkingas, nerūkytas. Apple CarPlay / Android Auto. Techninė apžiūra galioja iki 2026-02. Be dūmų, be rūdžių. Parkavimo jutikliai priekyje ir gale.",
    "attributes": {
      "make": "Volkswagen",
      "model": "Tiguan",
      "year": "2019",
      "mileage": "46 770 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Visureigis",
      "transmission": "Automatinė",
      "taExpiry": "2026-02",
      "vin": "WBAPMKHFDB97531ZX",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-015",
    "seller_id": "seller-auto-3",
    "title": "Volkswagen Touran 2001",
    "price": 1750,
    "location": "Pasvalys",
    "distance_km": 16.2,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volkswagen",
      "touran",
      "automobilis",
      "dyzelinas",
      "pasvalys"
    ],
    "has_video": false,
    "contact": "Tel. +370 61110866",
    "description": "Volkswagen Touran 2001 m. iš Pasvalys. Rida 256 158 km, dyzelinas, automatinė su padėtimis. Visi saugumo elementai veikia, paruošta registracijai. Parkavimo jutikliai priekyje ir gale. Serviso knygelė su visais įrašais. Vienas savininkas Lietuvoje. Automatinis parkavimas.",
    "attributes": {
      "make": "Volkswagen",
      "model": "Touran",
      "year": "2001",
      "mileage": "256 158 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Universalas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2025-03",
      "vin": "WBA7531ZXVTRNLJGE",
      "defects": "Nėra"
    },
    "provider_verified": true,
    "vin_verified": true
  },
  {
    "id": "lt-auto-016",
    "seller_id": "seller-auto-4",
    "title": "Volvo V70 2008",
    "price": 11050,
    "location": "Visaginas",
    "distance_km": 17.5,
    "image": "https://images.unsplash.com/photo-1619760133404-416b4bef3979?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volvo",
      "v70",
      "automobilis",
      "dyzelinas",
      "visaginas"
    ],
    "has_video": false,
    "contact": "Tel. +370 61118785",
    "description": "Volvo V70 2008 m. iš Visaginas. Rida 208 233 km, dyzelinas, mechaninė. Kėbulo būklė puiki, keli kosmetiniai pabraižymai. Automatinis parkavimas. Du raktelių komplektas. Importuota iš Vokietijos, tvarkinga istorija. Xenon/LED priekiniai žibintai.",
    "attributes": {
      "make": "Volvo",
      "model": "V70",
      "year": "2008",
      "mileage": "208 233 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Universalas",
      "transmission": "Mechaninė",
      "taExpiry": "2026-04",
      "vin": "WBARNLJGECA86420Y",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": false
  },
  {
    "id": "lt-auto-017",
    "seller_id": "seller-auto-5",
    "title": "Volvo XC60 2015",
    "price": 19600,
    "location": "Kaunas",
    "distance_km": 18.8,
    "image": "https://images.unsplash.com/photo-1619760133404-416b4bef3979?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volvo",
      "xc60",
      "automobilis",
      "dyzelinas",
      "kaunas"
    ],
    "has_video": false,
    "contact": "Tel. +370 61126704",
    "description": "Volvo XC60 2015 m. iš Kaunas. Rida 119 250 km, dyzelinas, automatinė. Be eismo įvykių, originali dažų spalva. Xenon/LED priekiniai žibintai. Naujos vasarinės padangos. Neseniai atlikta didžioji TO. Start-stop sistema, mažos sąnaudos.",
    "attributes": {
      "make": "Volvo",
      "model": "XC60",
      "year": "2015",
      "mileage": "119 250 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Visureigis",
      "transmission": "Automatinė",
      "taExpiry": "2025-05",
      "vin": "WBA86420YWUSPMKHF",
      "defects": "Smulkūs kosmetiniai defektai"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-018",
    "seller_id": "seller-auto-6",
    "title": "Volvo XC90 2022",
    "price": 35000,
    "location": "Panevėžys",
    "distance_km": 20.1,
    "image": "https://images.unsplash.com/photo-1619760133404-416b4bef3979?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volvo",
      "xc90",
      "automobilis",
      "dyzelinas",
      "panevėžys"
    ],
    "has_video": false,
    "contact": "Tel. +370 61134623",
    "description": "Volvo XC90 2022 m. iš Panevėžys. Rida 28 769 km, dyzelinas, automatinė su padėtimis. Priekinis buferis dažytas, techniškai tvarkinga. Start-stop sistema, mažos sąnaudos. Klimato kontrolė, šildomos sėdynės. Nauja vairo traukė, stabdžių diskai. 4×4 visų ratų pavara.",
    "attributes": {
      "make": "Volvo",
      "model": "XC90",
      "year": "2022",
      "mileage": "28 769 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Visureigis",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2026-06",
      "vin": "WBASPMKHFDB97531Z",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-019",
    "seller_id": "seller-auto-7",
    "title": "Volvo S60 2004",
    "price": 2800,
    "location": "Mažeikiai",
    "distance_km": 21.4,
    "image": "https://images.unsplash.com/photo-1619760133404-416b4bef3979?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volvo",
      "s60",
      "automobilis",
      "benzinas",
      "mažeikiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 61142542",
    "description": "Volvo S60 2004 m. iš Mažeikiai. Rida 182 225 km, benzinas, mechaninė. Salonas labai tvarkingas, nerūkytas. 4×4 visų ratų pavara. Navigacija, atbulinės kameros. Odinis salonas, panoraminis stogas. Automatinė bagažinės dangtis.",
    "attributes": {
      "make": "Volvo",
      "model": "S60",
      "year": "2004",
      "mileage": "182 225 km",
      "fuelType": "Benzinas",
      "bodyType": "Sedanas",
      "transmission": "Mechaninė",
      "taExpiry": "2025-07",
      "vin": "WBA97531ZXVTRNLJG",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": false
  },
  {
    "id": "lt-auto-020",
    "seller_id": "seller-auto-8",
    "title": "Toyota Corolla 2011",
    "price": 15000,
    "location": "Kupiškis",
    "distance_km": 22.7,
    "image": "https://images.unsplash.com/photo-1621007940902-bb6befaef932?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "toyota",
      "corolla",
      "automobilis",
      "hibridas",
      "kupiškis"
    ],
    "has_video": false,
    "contact": "Tel. +370 61150461",
    "description": "Toyota Corolla 2011 m. iš Kupiškis. Rida 149 098 km, hibridas, automatinė. Visi saugumo elementai veikia, paruošta registracijai. Automatinė bagažinės dangtis. LED žibintai, lietaus jutiklis. Apple CarPlay / Android Auto. Techninė apžiūra galioja iki 2026-08.",
    "attributes": {
      "make": "Toyota",
      "model": "Corolla",
      "year": "2011",
      "mileage": "149 098 km",
      "fuelType": "Hibridas",
      "bodyType": "Hečbekas",
      "transmission": "Automatinė",
      "taExpiry": "2026-08",
      "vin": "WBATRNLJGECA86420",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-021",
    "seller_id": "seller-auto-9",
    "title": "Toyota Avensis 2018",
    "price": 20750,
    "location": "Ukmergė",
    "distance_km": 21,
    "image": "https://images.unsplash.com/photo-1621007940902-bb6befaef932?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "toyota",
      "avensis",
      "automobilis",
      "dyzelinas",
      "ukmergė"
    ],
    "has_video": false,
    "contact": "Tel. +370 61158380",
    "description": "Toyota Avensis 2018 m. iš Ukmergė. Rida 74 473 km, dyzelinas, automatinė su padėtimis. Kėbulo būklė puiki, keli kosmetiniai pabraižymai. Techninė apžiūra galioja iki 2027-09. Be dūmų, be rūdžių. Parkavimo jutikliai priekyje ir gale. Serviso knygelė su visais įrašais.",
    "attributes": {
      "make": "Toyota",
      "model": "Avensis",
      "year": "2018",
      "mileage": "74 473 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Universalas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2025-09",
      "vin": "WBAA86420YWUSPMKH",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-022",
    "seller_id": "seller-auto-10",
    "title": "Toyota RAV4 2000",
    "price": 3100,
    "location": "Kėdainiai",
    "distance_km": 22.3,
    "image": "https://images.unsplash.com/photo-1621007940902-bb6befaef932?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "toyota",
      "rav4",
      "automobilis",
      "hibridas",
      "kėdainiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 61166299",
    "description": "Toyota RAV4 2000 m. iš Kėdainiai. Rida 257 305 km, hibridas, mechaninė. Be eismo įvykių, originali dažų spalva. Serviso knygelė su visais įrašais. Vienas savininkas Lietuvoje. Automatinis parkavimas. Du raktelių komplektas.",
    "attributes": {
      "make": "Toyota",
      "model": "RAV4",
      "year": "2000",
      "mileage": "257 305 km",
      "fuelType": "Hibridas",
      "bodyType": "Visureigis",
      "transmission": "Mechaninė",
      "taExpiry": "2026-10",
      "vin": "WBAUSPMKHFDB97531",
      "defects": "Nėra"
    },
    "provider_verified": true,
    "vin_verified": false
  },
  {
    "id": "lt-auto-023",
    "seller_id": "seller-auto-11",
    "title": "Toyota Yaris 2007",
    "price": 12700,
    "location": "Pasvalys",
    "distance_km": 23.6,
    "image": "https://images.unsplash.com/photo-1621007940902-bb6befaef932?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "toyota",
      "yaris",
      "automobilis",
      "benzinas",
      "pasvalys"
    ],
    "has_video": false,
    "contact": "Tel. +370 61174218",
    "description": "Toyota Yaris 2007 m. iš Pasvalys. Rida 206 314 km, benzinas, automatinė. Priekinis buferis dažytas, techniškai tvarkinga. Du raktelių komplektas. Importuota iš Vokietijos, tvarkinga istorija. Xenon/LED priekiniai žibintai. Naujos vasarinės padangos.",
    "attributes": {
      "make": "Toyota",
      "model": "Yaris",
      "year": "2007",
      "mileage": "206 314 km",
      "fuelType": "Benzinas",
      "bodyType": "Hečbekas",
      "transmission": "Automatinė",
      "taExpiry": "2025-11",
      "vin": "WBAB97531ZXVTRNLJ",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-auto-024",
    "seller_id": "seller-auto-12",
    "title": "Mercedes-Benz C220 d 2014",
    "price": 19950,
    "location": "Visaginas",
    "distance_km": 24.9,
    "image": "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "mercedes-benz",
      "c220",
      "automobilis",
      "dyzelinas",
      "visaginas"
    ],
    "has_video": false,
    "contact": "Tel. +370 61182137",
    "description": "Mercedes-Benz C220 d 2014 m. iš Visaginas. Rida 152 545 km, dyzelinas, automatinė su padėtimis. Salonas labai tvarkingas, nerūkytas. Naujos vasarinės padangos. Neseniai atlikta didžioji TO. Start-stop sistema, mažos sąnaudos. Klimato kontrolė, šildomos sėdynės.",
    "attributes": {
      "make": "Mercedes-Benz",
      "model": "C220 d",
      "year": "2014",
      "mileage": "152 545 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Sedanas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2026-12",
      "vin": "WBAVTRNLJGECA8642",
      "defects": "Nėra"
    },
    "provider_verified": false,
    "vin_verified": true
  },
  {
    "id": "lt-nt-001",
    "seller_id": "seller-nt-1",
    "title": "2 kambarių butas su balkonu",
    "price": 145000,
    "location": "Alytus",
    "distance_km": 11,
    "image": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "butas",
      "nt",
      "nuomai",
      "alytus",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64000000",
    "description": "2 kambarių butas su balkonu — Alytus. Plotas 54 m², 2 kamb. Butas. Puiki vieta, šalia infrastruktūra, transportas.",
    "attributes": {
      "propertyType": "Butas",
      "rooms": "2",
      "area": "54 m²"
    }
  },
  {
    "id": "lt-nt-002",
    "seller_id": "seller-nt-2",
    "title": "3 kambarių butas naujame name",
    "price": 198000,
    "location": "Mažeikiai",
    "distance_km": 12.3,
    "image": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "butas",
      "nt",
      "naujas",
      "mažeikiai",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64007919",
    "description": "Parduodamas butas Mažeikiai mieste. 3 kamb., 72 m². Tvarkinga būklė, galima apžiūrėti sutartu laiku.",
    "attributes": {
      "propertyType": "Butas",
      "rooms": "3",
      "area": "72 m²"
    }
  },
  {
    "id": "lt-nt-003",
    "seller_id": "seller-nt-3",
    "title": "Šiuolaikiškas loftas centre",
    "price": 235000,
    "location": "Utena",
    "distance_km": 13.6,
    "image": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "loftas",
      "nt",
      "centras",
      "utena",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64015838",
    "description": "Šiuolaikiškas loftas centre Utena rajone. 68 m², Butas. Skaidri dokumentacija, padėsime su paskola.",
    "attributes": {
      "propertyType": "Butas",
      "rooms": "2",
      "area": "68 m²"
    }
  },
  {
    "id": "lt-nt-004",
    "seller_id": "seller-nt-4",
    "title": "1 kambario butas studentams",
    "price": 89000,
    "location": "Telšiai",
    "distance_km": 14.9,
    "image": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "butas",
      "nt",
      "nuomai",
      "telšiai",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64023757",
    "description": "NT pasiūlymas Telšiai: 1 kambario butas studentams. 1 kamb., 32 m². Tinka gyvenimui ar investicijai.",
    "attributes": {
      "propertyType": "Butas",
      "rooms": "1",
      "area": "32 m²"
    }
  },
  {
    "id": "lt-nt-005",
    "seller_id": "seller-nt-5",
    "title": "Individualus namas su garažu",
    "price": 285000,
    "location": "Ukmergė",
    "distance_km": 16.2,
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "namas",
      "nt",
      "sklypas",
      "ukmergė",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64031676",
    "description": "Individualus namas su garažu — Ukmergė. Plotas 145 m², 4 kamb. Namas. Puiki vieta, šalia infrastruktūra, transportas.",
    "attributes": {
      "propertyType": "Namas",
      "rooms": "4",
      "area": "145 m²"
    }
  },
  {
    "id": "lt-nt-006",
    "seller_id": "seller-nt-6",
    "title": "Namas Priemiestyje su terasa",
    "price": 320000,
    "location": "Jonava",
    "distance_km": 17.5,
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "namas",
      "nt",
      "terasa",
      "jonava",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64039595",
    "description": "Parduodamas namas Jonava mieste. 5 kamb., 168 m². Tvarkinga būklė, galima apžiūrėti sutartu laiku.",
    "attributes": {
      "propertyType": "Namas",
      "rooms": "5",
      "area": "168 m²"
    }
  },
  {
    "id": "lt-nt-007",
    "seller_id": "seller-nt-1",
    "title": "Kotedžas dviems šeimoms",
    "price": 265000,
    "location": "Druskininkai",
    "distance_km": 18.8,
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "kotedžas",
      "nt",
      "druskininkai",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64047514",
    "description": "Kotedžas dviems šeimoms Druskininkai rajone. 190 m², Namas. Skaidri dokumentacija, padėsime su paskola.",
    "attributes": {
      "propertyType": "Namas",
      "rooms": "6",
      "area": "190 m²"
    }
  },
  {
    "id": "lt-nt-008",
    "seller_id": "seller-nt-2",
    "title": "Sklypas statybai 12 a",
    "price": 42000,
    "location": "Pasvalys",
    "distance_km": 20.1,
    "image": "https://images.unsplash.com/photo-1500382017468-90403fed94c1?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "sklypas",
      "nt",
      "statyba",
      "pasvalys",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64055433",
    "description": "NT pasiūlymas Pasvalys: Sklypas statybai 12 a. — kamb., 12 a. Tinka gyvenimui ar investicijai.",
    "attributes": {
      "propertyType": "Sklypas",
      "rooms": "—",
      "area": "12 a"
    }
  },
  {
    "id": "lt-nt-009",
    "seller_id": "seller-nt-3",
    "title": "Komercinės patalpos centre",
    "price": 175000,
    "location": "Kretinga",
    "distance_km": 21.4,
    "image": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "komercinis",
      "nt",
      "biuras",
      "kretinga",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64063352",
    "description": "Komercinės patalpos centre — Kretinga. Plotas 110 m², — kamb. Komercinis. Puiki vieta, šalia infrastruktūra, transportas.",
    "attributes": {
      "propertyType": "Komercinis",
      "rooms": "—",
      "area": "110 m²"
    }
  },
  {
    "id": "lt-nt-010",
    "seller_id": "seller-nt-4",
    "title": "Butas nuomai — įrengtas",
    "price": 650,
    "price_label": "650€/mėn.",
    "location": "Šilutė",
    "distance_km": 22.7,
    "image": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "nuoma",
      "nt",
      "butas",
      "šilutė",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64071271",
    "description": "Parduodamas nuoma Šilutė mieste. 2 kamb., 48 m². Tvarkinga būklė, galima apžiūrėti sutartu laiku.",
    "attributes": {
      "propertyType": "Nuoma",
      "rooms": "2",
      "area": "48 m²"
    }
  },
  {
    "id": "lt-nt-011",
    "seller_id": "seller-nt-5",
    "title": "Kambarys bendrame bute",
    "price": 220,
    "price_label": "220€/mėn.",
    "location": "Kaunas",
    "distance_km": 21,
    "image": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "nuoma",
      "kambarys",
      "nt",
      "kaunas",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64079190",
    "description": "Kambarys bendrame bute Kaunas rajone. 14 m², Nuoma. Skaidri dokumentacija, padėsime su paskola.",
    "attributes": {
      "propertyType": "Nuoma",
      "rooms": "1",
      "area": "14 m²"
    }
  },
  {
    "id": "lt-nt-012",
    "seller_id": "seller-nt-6",
    "title": "Sodyba su pirtimi ir sodu",
    "price": 155000,
    "location": "Šiauliai",
    "distance_km": 22.3,
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "sodyba",
      "nt",
      "pirtis",
      "šiauliai",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64087109",
    "description": "NT pasiūlymas Šiauliai: Sodyba su pirtimi ir sodu. 3 kamb., 95 m². Tinka gyvenimui ar investicijai.",
    "attributes": {
      "propertyType": "Namas",
      "rooms": "3",
      "area": "95 m²"
    }
  },
  {
    "id": "lt-nt-013",
    "seller_id": "seller-nt-1",
    "title": "4 kambarių butas su parkingu",
    "price": 215000,
    "location": "Alytus",
    "distance_km": 23.6,
    "image": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "butas",
      "nt",
      "parkingas",
      "alytus",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64095028",
    "description": "4 kambarių butas su parkingu — Alytus. Plotas 88 m², 4 kamb. Butas. Puiki vieta, šalia infrastruktūra, transportas.",
    "attributes": {
      "propertyType": "Butas",
      "rooms": "4",
      "area": "88 m²"
    }
  },
  {
    "id": "lt-nt-014",
    "seller_id": "seller-nt-2",
    "title": "Žemės sklypas ūkio paskirčiai",
    "price": 28000,
    "location": "Mažeikiai",
    "distance_km": 24.9,
    "image": "https://images.unsplash.com/photo-1500382017468-90403fed94c1?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "žemė",
      "nt",
      "sklypas",
      "mažeikiai",
      "nekilnojamasis"
    ],
    "has_video": false,
    "contact": "Tel. +370 64102947",
    "description": "Parduodamas sklypas Mažeikiai mieste. — kamb., 30 a. Tvarkinga būklė, galima apžiūrėti sutartu laiku.",
    "attributes": {
      "propertyType": "Sklypas",
      "rooms": "—",
      "area": "30 a"
    }
  },
  {
    "id": "lt-job-001",
    "seller_id": "seller-job-1",
    "title": "Vairuotojas CE — tarptautiniai reisai",
    "price": 0,
    "price_label": "nuo 1800€/mėn.",
    "location": "Mažeikiai",
    "distance_km": 21,
    "image": "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "vairuotojas",
      "darbas",
      "ce",
      "mažeikiai",
      "karjera"
    ],
    "has_video": false,
    "contact": "Tel. +370 65000000",
    "description": "Vairuotojas CE — tarptautiniai reisai — Mažeikiai ir apylinkės. Etatas: Pamainos. Patirtis: 2+ m..",
    "attributes": {
      "position": "Vairuotojas",
      "schedule": "Pamainos",
      "experience": "2+ m."
    }
  },
  {
    "id": "lt-job-002",
    "seller_id": "seller-job-2",
    "title": "Sandėlininkas — naktinės pamainos",
    "price": 0,
    "price_label": "nuo 1200€/mėn.",
    "location": "Kupiškis",
    "distance_km": 22.3,
    "image": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "sandėlis",
      "darbas",
      "logistika",
      "kupiškis",
      "karjera"
    ],
    "has_video": false,
    "contact": "Tel. +370 65007919",
    "description": "Ieškome Sandėlininkas Kupiškis. nuo 1200€/mėn.. Suteikiame apmokymą.",
    "attributes": {
      "position": "Sandėlininkas",
      "schedule": "Naktinis",
      "experience": "Be patirties"
    }
  },
  {
    "id": "lt-job-003",
    "seller_id": "seller-job-3",
    "title": "PHP programuotojas (Symfony)",
    "price": 0,
    "price_label": "2500–4000€/mėn.",
    "location": "Ukmergė",
    "distance_km": 23.6,
    "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "programuotojas",
      "it",
      "darbas",
      "ukmergė",
      "karjera"
    ],
    "has_video": false,
    "contact": "Tel. +370 65015838",
    "description": "Darbo pasiūlymas: PHP programuotojas (Symfony). Vieta: Ukmergė. Grafikas: Hibridas. Kreipkitės su CV.",
    "attributes": {
      "position": "Programuotojas",
      "schedule": "Hibridas",
      "experience": "3+ m."
    }
  },
  {
    "id": "lt-job-004",
    "seller_id": "seller-job-4",
    "title": "Virėjas — restoranas centre",
    "price": 0,
    "price_label": "nuo 1400€/mėn.",
    "location": "Kėdainiai",
    "distance_km": 24.9,
    "image": "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "virėjas",
      "maistas",
      "darbas",
      "kėdainiai",
      "karjera"
    ],
    "has_video": false,
    "contact": "Tel. +370 65023757",
    "description": "Virėjas pozicija Kėdainiai. Virėjas — restoranas centre. Oficialus įdarbinimas, socialinės garantijos.",
    "attributes": {
      "position": "Virėjas",
      "schedule": "Pilnas etatas",
      "experience": "1+ m."
    }
  },
  {
    "id": "lt-job-005",
    "seller_id": "seller-job-5",
    "title": "Medicinos seselė — slaugos skyrius",
    "price": 0,
    "price_label": "nuo 1600€/mėn.",
    "location": "Pasvalys",
    "distance_km": 26.2,
    "image": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "slauga",
      "medicina",
      "darbas",
      "pasvalys",
      "karjera"
    ],
    "has_video": false,
    "contact": "Tel. +370 65031676",
    "description": "Medicinos seselė — slaugos skyrius — Pasvalys ir apylinkės. Etatas: Pamainos. Patirtis: 2+ m..",
    "attributes": {
      "position": "Seselė",
      "schedule": "Pamainos",
      "experience": "2+ m."
    }
  },
  {
    "id": "lt-job-006",
    "seller_id": "seller-job-1",
    "title": "Statybų darbų vadovas",
    "price": 0,
    "price_label": "nuo 2200€/mėn.",
    "location": "Visaginas",
    "distance_km": 27.5,
    "image": "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "statyba",
      "vadovas",
      "darbas",
      "visaginas",
      "karjera"
    ],
    "has_video": false,
    "contact": "Tel. +370 65039595",
    "description": "Ieškome Vadovas Visaginas. nuo 2200€/mėn.. Suteikiame apmokymą.",
    "attributes": {
      "position": "Vadovas",
      "schedule": "Pilnas etatas",
      "experience": "5+ m."
    }
  },
  {
    "id": "lt-job-007",
    "seller_id": "seller-job-2",
    "title": "Pardavėjas-consultant elektronikos salėje",
    "price": 0,
    "price_label": "nuo 1100€/mėn.",
    "location": "Kaunas",
    "distance_km": 28.8,
    "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "pardavimas",
      "darbas",
      "retail",
      "kaunas",
      "karjera"
    ],
    "has_video": false,
    "contact": "Tel. +370 65047514",
    "description": "Darbo pasiūlymas: Pardavėjas-consultant elektronikos salėje. Vieta: Kaunas. Grafikas: Pamainos. Kreipkitės su CV.",
    "attributes": {
      "position": "Pardavėjas",
      "schedule": "Pamainos",
      "experience": "Be patirties"
    }
  },
  {
    "id": "lt-job-008",
    "seller_id": "seller-job-3",
    "title": "Buhalterė — maža įmonė",
    "price": 0,
    "price_label": "nuo 1500€/mėn.",
    "location": "Panevėžys",
    "distance_km": 30.1,
    "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "buhalterija",
      "darbas",
      "finansai",
      "panevėžys",
      "karjera"
    ],
    "has_video": false,
    "contact": "Tel. +370 65055433",
    "description": "Buhalterė pozicija Panevėžys. Buhalterė — maža įmonė. Oficialus įdarbinimas, socialinės garantijos.",
    "attributes": {
      "position": "Buhalterė",
      "schedule": "Pilnas etatas",
      "experience": "3+ m."
    }
  },
  {
    "id": "lt-job-009",
    "seller_id": "seller-job-4",
    "title": "Kurjeris — nuosavas automobilis",
    "price": 0,
    "price_label": "nuo 1000€/mėn.",
    "location": "Mažeikiai",
    "distance_km": 31.4,
    "image": "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "kurjeris",
      "logistika",
      "darbas",
      "mažeikiai",
      "karjera"
    ],
    "has_video": false,
    "contact": "Tel. +370 65063352",
    "description": "Kurjeris — nuosavas automobilis — Mažeikiai ir apylinkės. Etatas: Lankstus. Patirtis: Be patirties.",
    "attributes": {
      "position": "Kurjeris",
      "schedule": "Lankstus",
      "experience": "Be patirties"
    }
  },
  {
    "id": "lt-job-010",
    "seller_id": "seller-job-5",
    "title": "Suvirintojas TIG/MIG",
    "price": 0,
    "price_label": "nuo 1700€/mėn.",
    "location": "Kupiškis",
    "distance_km": 32.7,
    "image": "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "suvirintojas",
      "gamykla",
      "darbas",
      "kupiškis",
      "karjera"
    ],
    "has_video": false,
    "contact": "Tel. +370 65071271",
    "description": "Ieškome Suvirintojas Kupiškis. nuo 1700€/mėn.. Suteikiame apmokymą.",
    "attributes": {
      "position": "Suvirintojas",
      "schedule": "Pamainos",
      "experience": "2+ m."
    }
  },
  {
    "id": "lt-job-011",
    "seller_id": "seller-job-1",
    "title": "Klientų aptarnavimo specialistas",
    "price": 0,
    "price_label": "nuo 1150€/mėn.",
    "location": "Ukmergė",
    "distance_km": 31,
    "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "support",
      "darbas",
      "biuras",
      "ukmergė",
      "karjera"
    ],
    "has_video": false,
    "contact": "Tel. +370 65079190",
    "description": "Darbo pasiūlymas: Klientų aptarnavimo specialistas. Vieta: Ukmergė. Grafikas: Pamainos. Kreipkitės su CV.",
    "attributes": {
      "position": "Specialistas",
      "schedule": "Pamainos",
      "experience": "1+ m."
    }
  },
  {
    "id": "lt-job-012",
    "seller_id": "seller-job-2",
    "title": "Auklė / babysitter — nuolatinė",
    "price": 0,
    "price_label": "nuo 900€/mėn.",
    "location": "Kėdainiai",
    "distance_km": 32.3,
    "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "auklė",
      "darbas",
      "vaikai",
      "kėdainiai",
      "karjera"
    ],
    "has_video": false,
    "contact": "Tel. +370 65087109",
    "description": "Auklė pozicija Kėdainiai. Auklė / babysitter — nuolatinė. Oficialus įdarbinimas, socialinės garantijos.",
    "attributes": {
      "position": "Auklė",
      "schedule": "Pilnas etatas",
      "experience": "2+ m."
    }
  },
  {
    "id": "lt-clo-001",
    "seller_id": "seller-clo-1",
    "title": "Nike Air Max 270 batai 43 d.",
    "price": 85,
    "location": "Kaunas",
    "distance_km": 31,
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "nike",
      "batai",
      "sportas",
      "kaunas",
      "drabužiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 66000000",
    "description": "Parduodu Nike Air Max 270 batai 43 d.. Dydis 43, būklė: Gera. Kaunas, galiu siųsti LP Express.",
    "attributes": {
      "brand": "Nike",
      "size": "43",
      "condition": "Gera"
    }
  },
  {
    "id": "lt-clo-002",
    "seller_id": "seller-clo-2",
    "title": "Zara vilnonė striukė M",
    "price": 45,
    "location": "Alytus",
    "distance_km": 32.3,
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "zara",
      "striukė",
      "drabužiai",
      "alytus",
      "drabužiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 66007919",
    "description": "Zara vilnonė striukė M — Zara prekė. Dydis M. Naudota kelis kartus, be defektų. Alytus.",
    "attributes": {
      "brand": "Zara",
      "size": "M",
      "condition": "Kaip nauja"
    }
  },
  {
    "id": "lt-clo-003",
    "seller_id": "seller-clo-3",
    "title": "Mango suknelė vakariniam renginiui",
    "price": 38,
    "location": "Utena",
    "distance_km": 33.6,
    "image": "https://images.unsplash.com/photo-1595777457583-95e0591d1b72?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "mango",
      "suknelė",
      "drabužiai",
      "utena",
      "drabužiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 66015838",
    "description": "Tvarkingas mango suknelė vakariniam renginiui, dydis S. Originalus, ne fake. Perduodu Utena centre.",
    "attributes": {
      "brand": "Mango",
      "size": "S",
      "condition": "Nauja"
    }
  },
  {
    "id": "lt-clo-004",
    "seller_id": "seller-clo-4",
    "title": "Levi's 501 džinsai W32 L32",
    "price": 42,
    "location": "Ukmergė",
    "distance_km": 34.9,
    "image": "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "levis",
      "džinsai",
      "drabužiai",
      "ukmergė",
      "drabužiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 66023757",
    "description": "Levi's 501 džinsai W32 L32. Būklė: Gera. Dydis W32 L32. Ukmergė, galimas siuntimas.",
    "attributes": {
      "brand": "Levi's",
      "size": "W32 L32",
      "condition": "Gera"
    }
  },
  {
    "id": "lt-clo-005",
    "seller_id": "seller-clo-5",
    "title": "North Face žieminė striukė L",
    "price": 120,
    "location": "Druskininkai",
    "distance_km": 36.2,
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "north face",
      "striukė",
      "žiemą",
      "druskininkai",
      "drabužiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 66031676",
    "description": "Parduodu North Face žieminė striukė L. Dydis L, būklė: Labai gera. Druskininkai, galiu siųsti LP Express.",
    "attributes": {
      "brand": "The North Face",
      "size": "L",
      "condition": "Labai gera"
    }
  },
  {
    "id": "lt-clo-006",
    "seller_id": "seller-clo-1",
    "title": "Adidas Ultraboost batai 42 d.",
    "price": 95,
    "location": "Kretinga",
    "distance_km": 37.5,
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "adidas",
      "batai",
      "bėgimas",
      "kretinga",
      "drabužiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 66039595",
    "description": "Adidas Ultraboost batai 42 d. — Adidas prekė. Dydis 42. Naudota kelis kartus, be defektų. Kretinga.",
    "attributes": {
      "brand": "Adidas",
      "size": "42",
      "condition": "Gera"
    }
  },
  {
    "id": "lt-clo-007",
    "seller_id": "seller-clo-2",
    "title": "Michael Kors rankinė",
    "price": 75,
    "location": "Kaunas",
    "distance_km": 38.8,
    "image": "https://images.unsplash.com/photo-1584917865442-de89a76edc7b?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "rankinė",
      "moteriška",
      "aksesuaras",
      "kaunas",
      "drabužiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 66047514",
    "description": "Tvarkingas michael kors rankinė, dydis —. Originalus, ne fake. Perduodu Kaunas centre.",
    "attributes": {
      "brand": "Michael Kors",
      "size": "—",
      "condition": "Kaip nauja"
    }
  },
  {
    "id": "lt-clo-008",
    "seller_id": "seller-clo-3",
    "title": "H&M vaikiška striukė 128 cm",
    "price": 18,
    "location": "Alytus",
    "distance_km": 40.1,
    "image": "https://images.unsplash.com/photo-1519236762933-8a98c0a5d393?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "vaikai",
      "striukė",
      "drabužiai",
      "alytus",
      "drabužiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 66055433",
    "description": "H&M vaikiška striukė 128 cm. Būklė: Gera. Dydis 128. Alytus, galimas siuntimas.",
    "attributes": {
      "brand": "H&M",
      "size": "128",
      "condition": "Gera"
    }
  },
  {
    "id": "lt-clo-009",
    "seller_id": "seller-clo-4",
    "title": "Tommy Hilfiger polo marškinėliai",
    "price": 28,
    "location": "Utena",
    "distance_km": 41.4,
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "tommy",
      "marškinėliai",
      "drabužiai",
      "utena",
      "drabužiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 66063352",
    "description": "Parduodu Tommy Hilfiger polo marškinėliai. Dydis L, būklė: Nauja. Utena, galiu siųsti LP Express.",
    "attributes": {
      "brand": "Tommy Hilfiger",
      "size": "L",
      "condition": "Nauja"
    }
  },
  {
    "id": "lt-clo-010",
    "seller_id": "seller-clo-5",
    "title": "Puma sportiniai kostiumai",
    "price": 55,
    "location": "Ukmergė",
    "distance_km": 42.7,
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "puma",
      "sportas",
      "drabužiai",
      "ukmergė",
      "drabužiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 66071271",
    "description": "Puma sportiniai kostiumai — Puma prekė. Dydis M. Naudota kelis kartus, be defektų. Ukmergė.",
    "attributes": {
      "brand": "Puma",
      "size": "M",
      "condition": "Gera"
    }
  },
  {
    "id": "lt-clo-011",
    "seller_id": "seller-clo-1",
    "title": "Timberland aulinukai 44 d.",
    "price": 110,
    "location": "Druskininkai",
    "distance_km": 1,
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "timberland",
      "batai",
      "žiemą",
      "druskininkai",
      "drabužiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 66079190",
    "description": "Tvarkingas timberland aulinukai 44 d., dydis 44. Originalus, ne fake. Perduodu Druskininkai centre.",
    "attributes": {
      "brand": "Timberland",
      "size": "44",
      "condition": "Labai gera"
    }
  },
  {
    "id": "lt-clo-012",
    "seller_id": "seller-clo-2",
    "title": "Reserved palto modelis moterims",
    "price": 68,
    "location": "Kretinga",
    "distance_km": 2.3,
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "reserved",
      "paltas",
      "drabužiai",
      "kretinga",
      "drabužiai"
    ],
    "has_video": false,
    "contact": "Tel. +370 66087109",
    "description": "Reserved palto modelis moterims. Būklė: Gera. Dydis M. Kretinga, galimas siuntimas.",
    "attributes": {
      "brand": "Reserved",
      "size": "M",
      "condition": "Gera"
    }
  },
  {
    "id": "lt-el-001",
    "seller_id": "seller-el-1",
    "title": "iPhone 15 Pro 256 GB",
    "price": 980,
    "location": "Klaipėda",
    "distance_km": 1,
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "iphone",
      "telefonas",
      "apple",
      "klaipėda",
      "elektronika"
    ],
    "has_video": false,
    "contact": "Tel. +370 62000000",
    "description": "Parduodu iPhone 15 Pro 256 GB — naudotas, bet be defektų. Ekranas be įbrėžimų, baterija laiko puikiai. Komplektas su dėklu ir įkrovikliu. Galima apžiūrėti Klaipėda."
  },
  {
    "id": "lt-el-002",
    "seller_id": "seller-el-2",
    "title": "iPhone 14 128 GB",
    "price": 650,
    "location": "Mažeikiai",
    "distance_km": 2.3,
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "iphone",
      "telefonas",
      "mažeikiai",
      "elektronika"
    ],
    "has_video": false,
    "contact": "Tel. +370 62007919",
    "description": "iPhone 14 128 GB — pirktas oficialioje parduotuvėje, liko garantija. Visi priedai, dėžutė ir kvitas. Perduodu Mažeikiai centre."
  },
  {
    "id": "lt-el-003",
    "seller_id": "seller-el-3",
    "title": "Samsung Galaxy S24 Ultra",
    "price": 950,
    "location": "Tauragė",
    "distance_km": 3.6,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "samsung",
      "telefonas",
      "android",
      "tauragė",
      "elektronika"
    ],
    "has_video": false,
    "contact": "Tel. +370 62015838",
    "description": "Tvarkingas Samsung Galaxy S24 Ultra, naudotas namuose. Be vandens pažeidimų, visos funkcijos veikia. Greitas susitikimas Tauragė."
  },
  {
    "id": "lt-el-004",
    "seller_id": "seller-el-4",
    "title": "MacBook Air M2 13\"",
    "price": 1050,
    "location": "Druskininkai",
    "distance_km": 4.9,
    "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "macbook",
      "apple",
      "kompiuteris",
      "druskininkai",
      "elektronika"
    ],
    "has_video": false,
    "contact": "Tel. +370 62023757",
    "description": "MacBook Air M2 13\" — atnaujintas programinė įranga, Face ID/Touch ID veikia. Idealus kasdieniam naudojimui. Druskininkai, galiu atvežti."
  },
  {
    "id": "lt-el-005",
    "seller_id": "seller-el-5",
    "title": "iPad Pro 11\" M2",
    "price": 810,
    "location": "Visaginas",
    "distance_km": 6.2,
    "image": "https://images.unsplash.com/photo-1606144042614-b2417e99c4ee?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "ipad",
      "planšetė",
      "visaginas",
      "elektronika"
    ],
    "has_video": false,
    "contact": "Tel. +370 62031676",
    "description": "Parduodu iPad Pro 11\" M2 — naudotas, bet be defektų. Ekranas be įbrėžimų, baterija laiko puikiai. Komplektas su dėklu ir įkrovikliu. Galima apžiūrėti Visaginas."
  },
  {
    "id": "lt-el-006",
    "seller_id": "seller-el-1",
    "title": "PlayStation 5 + 2 pultai",
    "price": 480,
    "location": "Šiauliai",
    "distance_km": 7.5,
    "image": "https://images.unsplash.com/photo-1606813907291-d86efa9b397e?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "ps5",
      "žaidimai",
      "konsolė",
      "šiauliai",
      "elektronika"
    ],
    "has_video": false,
    "contact": "Tel. +370 62039595",
    "description": "PlayStation 5 + 2 pultai — pirktas oficialioje parduotuvėje, liko garantija. Visi priedai, dėžutė ir kvitas. Perduodu Šiauliai centre."
  },
  {
    "id": "lt-el-007",
    "seller_id": "seller-el-2",
    "title": "Dyson V15 Detect",
    "price": 480,
    "location": "Biržai",
    "distance_km": 8.8,
    "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "dyson",
      "siurblys",
      "namams",
      "biržai",
      "elektronika"
    ],
    "has_video": false,
    "contact": "Tel. +370 62047514",
    "description": "Tvarkingas Dyson V15 Detect, naudotas namuose. Be vandens pažeidimų, visos funkcijos veikia. Greitas susitikimas Biržai."
  },
  {
    "id": "lt-el-008",
    "seller_id": "seller-el-3",
    "title": "Sony WH-1000XM5 ausinės",
    "price": 290,
    "location": "Ukmergė",
    "distance_km": 10.1,
    "image": "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "sony",
      "ausinės",
      "bluetooth",
      "ukmergė",
      "elektronika"
    ],
    "has_video": false,
    "contact": "Tel. +370 62055433",
    "description": "Sony WH-1000XM5 ausinės — atnaujintas programinė įranga, Face ID/Touch ID veikia. Idealus kasdieniam naudojimui. Ukmergė, galiu atvežti."
  },
  {
    "id": "lt-el-009",
    "seller_id": "seller-el-4",
    "title": "iPhone 15 Pro 256 GB",
    "price": 1040,
    "location": "Rokiškis",
    "distance_km": 11.4,
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "iphone",
      "telefonas",
      "apple",
      "rokiškis",
      "elektronika"
    ],
    "has_video": false,
    "contact": "Tel. +370 62063352",
    "description": "Parduodu iPhone 15 Pro 256 GB — naudotas, bet be defektų. Ekranas be įbrėžimų, baterija laiko puikiai. Komplektas su dėklu ir įkrovikliu. Galima apžiūrėti Rokiškis."
  },
  {
    "id": "lt-el-010",
    "seller_id": "seller-el-5",
    "title": "iPhone 14 128 GB",
    "price": 620,
    "location": "Šilutė",
    "distance_km": 12.7,
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "iphone",
      "telefonas",
      "šilutė",
      "elektronika"
    ],
    "has_video": false,
    "contact": "Tel. +370 62071271",
    "description": "iPhone 14 128 GB — pirktas oficialioje parduotuvėje, liko garantija. Visi priedai, dėžutė ir kvitas. Perduodu Šilutė centre."
  },
  {
    "id": "lt-el-011",
    "seller_id": "seller-el-1",
    "title": "Samsung Galaxy S24 Ultra",
    "price": 920,
    "location": "Panevėžys",
    "distance_km": 11,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "samsung",
      "telefonas",
      "android",
      "panevėžys",
      "elektronika"
    ],
    "has_video": false,
    "contact": "Tel. +370 62079190",
    "description": "Tvarkingas Samsung Galaxy S24 Ultra, naudotas namuose. Be vandens pažeidimų, visos funkcijos veikia. Greitas susitikimas Panevėžys."
  },
  {
    "id": "lt-el-012",
    "seller_id": "seller-el-2",
    "title": "MacBook Air M2 13\"",
    "price": 1110,
    "location": "Utena",
    "distance_km": 12.3,
    "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "macbook",
      "apple",
      "kompiuteris",
      "utena",
      "elektronika"
    ],
    "has_video": false,
    "contact": "Tel. +370 62087109",
    "description": "MacBook Air M2 13\" — atnaujintas programinė įranga, Face ID/Touch ID veikia. Idealus kasdieniam naudojimui. Utena, galiu atvežti."
  },
  {
    "id": "lt-home-001",
    "seller_id": "seller-home-1",
    "title": "Sofa-lova su daiktų saugykla",
    "price": 420,
    "location": "Utena",
    "distance_km": 11,
    "image": "https://images.unsplash.com/photo-1555041469-a586c61e9bc7?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "sofa",
      "baldai",
      "svetainė",
      "utena",
      "baldai"
    ],
    "has_video": false,
    "contact": "Tel. +370 67000000",
    "description": "Parduodu sofa-lova su daiktų saugykla — Utena. Tvarkinga būklė, be įbrėžimų. Galimas pristatymas mieste."
  },
  {
    "id": "lt-home-002",
    "seller_id": "seller-home-2",
    "title": "Stiklo valgomojo stalas su 6 kėdėmis",
    "price": 380,
    "location": "Tauragė",
    "distance_km": 12.3,
    "image": "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "stalas",
      "baldai",
      "virtuvė",
      "tauragė",
      "baldai"
    ],
    "has_video": false,
    "contact": "Tel. +370 67007919",
    "description": "Stiklo valgomojo stalas su 6 kėdėmis iš Tauragė. Naudotas namuose, rūpestingai prižiūrėtas. Galite apžiūrėti gyvai."
  },
  {
    "id": "lt-home-003",
    "seller_id": "seller-home-3",
    "title": "Virtuvės komplektas — matinė balta",
    "price": 1850,
    "location": "Jonava",
    "distance_km": 13.6,
    "image": "https://images.unsplash.com/photo-1556909114-f6e7ad7d4046?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "virtuvė",
      "baldai",
      "komplektas",
      "jonava",
      "baldai"
    ],
    "has_video": false,
    "contact": "Tel. +370 67015838",
    "description": "Virtuvės komplektas — matinė balta — kokybiškas, funkcionalus. Jonava. Greitas atsiėmimas arba pristatymas."
  },
  {
    "id": "lt-home-004",
    "seller_id": "seller-home-4",
    "title": "King size lova su čiužiniu",
    "price": 650,
    "location": "Rokiškis",
    "distance_km": 14.9,
    "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "lova",
      "miegamasis",
      "baldai",
      "rokiškis",
      "baldai"
    ],
    "has_video": false,
    "contact": "Tel. +370 67023757",
    "description": "Baldų pasiūlymas: King size lova su čiužiniu. Vieta: Rokiškis. Be rūdžių, defektų ar stipresnio nusidėvėjimo."
  },
  {
    "id": "lt-home-005",
    "seller_id": "seller-home-1",
    "title": "Spinta-sliding 3 durų",
    "price": 520,
    "location": "Kretinga",
    "distance_km": 16.2,
    "image": "https://images.unsplash.com/photo-1595428774223-ef52624120ce?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "spinta",
      "baldai",
      "miegamasis",
      "kretinga",
      "baldai"
    ],
    "has_video": false,
    "contact": "Tel. +370 67031676",
    "description": "Parduodu spinta-sliding 3 durų — Kretinga. Tvarkinga būklė, be įbrėžimų. Galimas pristatymas mieste."
  },
  {
    "id": "lt-home-006",
    "seller_id": "seller-home-2",
    "title": "Ergonominė darbo kėdė",
    "price": 145,
    "location": "Vilnius",
    "distance_km": 17.5,
    "image": "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "kėdė",
      "biuras",
      "baldai",
      "vilnius",
      "baldai"
    ],
    "has_video": false,
    "contact": "Tel. +370 67039595",
    "description": "Ergonominė darbo kėdė iš Vilnius. Naudotas namuose, rūpestingai prižiūrėtas. Galite apžiūrėti gyvai."
  },
  {
    "id": "lt-home-007",
    "seller_id": "seller-home-3",
    "title": "TV komoda su LED apšvietimu",
    "price": 210,
    "location": "Šiauliai",
    "distance_km": 18.8,
    "image": "https://images.unsplash.com/photo-1555041469-a586c61e9bc7?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "komoda",
      "baldai",
      "svetainė",
      "šiauliai",
      "baldai"
    ],
    "has_video": false,
    "contact": "Tel. +370 67047514",
    "description": "TV komoda su LED apšvietimu — kokybiškas, funkcionalus. Šiauliai. Greitas atsiėmimas arba pristatymas."
  },
  {
    "id": "lt-home-008",
    "seller_id": "seller-home-4",
    "title": "Knygų lentyna 5 skyrių",
    "price": 95,
    "location": "Marijampolė",
    "distance_km": 20.1,
    "image": "https://images.unsplash.com/photo-1595428774223-ef52624120ce?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "lentyna",
      "baldai",
      "namai",
      "marijampolė",
      "baldai"
    ],
    "has_video": false,
    "contact": "Tel. +370 67055433",
    "description": "Baldų pasiūlymas: Knygų lentyna 5 skyrių. Vieta: Marijampolė. Be rūdžių, defektų ar stipresnio nusidėvėjimo."
  },
  {
    "id": "lt-home-009",
    "seller_id": "seller-home-1",
    "title": "Baro kėdės 2 vnt. metalinės",
    "price": 120,
    "location": "Utena",
    "distance_km": 21.4,
    "image": "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "kėdės",
      "baldai",
      "virtuvė",
      "utena",
      "baldai"
    ],
    "has_video": false,
    "contact": "Tel. +370 67063352",
    "description": "Parduodu baro kėdės 2 vnt. metalinės — Utena. Tvarkinga būklė, be įbrėžimų. Galimas pristatymas mieste."
  },
  {
    "id": "lt-home-010",
    "seller_id": "seller-home-2",
    "title": "Vaiko kambario komplektas",
    "price": 480,
    "location": "Tauragė",
    "distance_km": 22.7,
    "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "vaikams",
      "baldai",
      "kambarys",
      "tauragė",
      "baldai"
    ],
    "has_video": false,
    "contact": "Tel. +370 67071271",
    "description": "Vaiko kambario komplektas iš Tauragė. Naudotas namuose, rūpestingai prižiūrėtas. Galite apžiūrėti gyvai."
  },
  {
    "id": "lt-home-011",
    "seller_id": "seller-home-3",
    "title": "Šviestuvas + staliukas komplektas",
    "price": 165,
    "location": "Jonava",
    "distance_km": 21,
    "image": "https://images.unsplash.com/photo-1555041469-a586c61e9bc7?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "šviestuvas",
      "baldai",
      "svetainė",
      "jonava",
      "baldai"
    ],
    "has_video": false,
    "contact": "Tel. +370 67079190",
    "description": "Šviestuvas + staliukas komplektas — kokybiškas, funkcionalus. Jonava. Greitas atsiėmimas arba pristatymas."
  },
  {
    "id": "lt-svc-001",
    "seller_id": "seller-svc-1",
    "title": "Automobilio detailing — pilnas paketas",
    "price": 120,
    "price_label": "nuo 120€",
    "location": "Šiauliai",
    "distance_km": 21,
    "image": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "detailing",
      "plovimas",
      "automobilis",
      "šiauliai",
      "paslauga"
    ],
    "has_video": false,
    "contact": "Tel. +370 63000000",
    "description": "Automobilio detailing — pilnas paketas — dirbame Šiauliai ir apylinkėse. Profesionali įranga, sąskaitos faktūros. Skambinkite dėl laiko.",
    "provider_verified": true
  },
  {
    "id": "lt-svc-002",
    "seller_id": "seller-svc-2",
    "title": "Padangų montavimas ir balansavimas",
    "price": 35,
    "price_label": "nuo 35€",
    "location": "Mažeikiai",
    "distance_km": 22.3,
    "image": "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "padangos",
      "montavimas",
      "autoservisas",
      "mažeikiai",
      "paslauga"
    ],
    "has_video": false,
    "contact": "Tel. +370 63007919",
    "description": "Siūlome padangų montavimas ir balansavimas Mažeikiai regione. Greitas aptarnavimas, patyrę meistrai, garantija darbams.",
    "provider_verified": true
  },
  {
    "id": "lt-svc-003",
    "seller_id": "seller-svc-3",
    "title": "Paruošimas techninei apžiūrai",
    "price": 45,
    "price_label": "nuo 45€",
    "location": "Telšiai",
    "distance_km": 23.6,
    "image": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "ta",
      "techninė",
      "autoservisas",
      "telšiai",
      "paslauga"
    ],
    "has_video": false,
    "contact": "Tel. +370 63015838",
    "description": "Paruošimas techninei apžiūrai. Atvykstame į vietą Telšiai mieste. Skaidri kainodara, be paslėptų mokesčių.",
    "provider_verified": true
  },
  {
    "id": "lt-svc-004",
    "seller_id": "seller-svc-4",
    "title": "Santechnikas — avarinis iškvietimas",
    "price": 50,
    "price_label": "nuo 50€",
    "location": "Jonava",
    "distance_km": 24.9,
    "image": "https://images.unsplash.com/photo-1585704032915-e241ff423e8f?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "santechnikas",
      "remontas",
      "paslauga",
      "jonava",
      "paslauga"
    ],
    "has_video": false,
    "contact": "Tel. +370 63023757",
    "description": "Santechnikas — avarinis iškvietimas — ilgametė patirtis, rekomendacijos klientų. Jonava ir visa Lietuva.",
    "provider_verified": true
  },
  {
    "id": "lt-svc-005",
    "seller_id": "seller-svc-1",
    "title": "Elektrikas — rozetės, apšvietimas",
    "price": 40,
    "price_label": "nuo 40€",
    "location": "Pasvalys",
    "distance_km": 26.2,
    "image": "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "elektrikas",
      "montavimas",
      "pasvalys",
      "paslauga"
    ],
    "has_video": false,
    "contact": "Tel. +370 63031676",
    "description": "Elektrikas — rozetės, apšvietimas — dirbame Pasvalys ir apylinkėse. Profesionali įranga, sąskaitos faktūros. Skambinkite dėl laiko.",
    "provider_verified": true
  },
  {
    "id": "lt-svc-006",
    "seller_id": "seller-svc-2",
    "title": "Buto valymas po remonto",
    "price": 80,
    "price_label": "nuo 80€",
    "location": "Šilutė",
    "distance_km": 27.5,
    "image": "https://images.unsplash.com/photo-1581578731548-86083659925c?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "valymas",
      "butas",
      "paslauga",
      "šilutė",
      "paslauga"
    ],
    "has_video": false,
    "contact": "Tel. +370 63039595",
    "description": "Siūlome buto valymas po remonto Šilutė regione. Greitas aptarnavimas, patyrę meistrai, garantija darbams.",
    "provider_verified": true
  },
  {
    "id": "lt-svc-007",
    "seller_id": "seller-svc-3",
    "title": "Evacuatorius 24/7 visoje Lietuvoje",
    "price": 40,
    "price_label": "nuo 40€",
    "location": "Šiauliai",
    "distance_km": 28.8,
    "image": "https://images.unsplash.com/photo-1621939514649-280e2ee02577?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "evakuatorius",
      "pagalba",
      "kelyje",
      "šiauliai",
      "paslauga"
    ],
    "has_video": false,
    "contact": "Tel. +370 63047514",
    "description": "Evacuatorius 24/7 visoje Lietuvoje. Atvykstame į vietą Šiauliai mieste. Skaidri kainodara, be paslėptų mokesčių.",
    "provider_verified": true
  },
  {
    "id": "lt-svc-008",
    "seller_id": "seller-svc-4",
    "title": "Kėbulų dažymas — profesionaliai",
    "price": 350,
    "price_label": "nuo 350€",
    "location": "Mažeikiai",
    "distance_km": 30.1,
    "image": "https://images.unsplash.com/photo-1619642751034-765df69d01c9?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "dažymas",
      "kėbulas",
      "autoservisas",
      "mažeikiai",
      "paslauga"
    ],
    "has_video": false,
    "contact": "Tel. +370 63055433",
    "description": "Kėbulų dažymas — profesionaliai — ilgametė patirtis, rekomendacijos klientų. Mažeikiai ir visa Lietuva.",
    "provider_verified": true
  },
  {
    "id": "lt-svc-009",
    "seller_id": "seller-svc-1",
    "title": "Variklio diagnostika OBD",
    "price": 25,
    "price_label": "25€",
    "location": "Telšiai",
    "distance_km": 31.4,
    "image": "https://images.unsplash.com/photo-1625047509248-ec889cbff097?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "diagnostika",
      "obd",
      "autoservisas",
      "telšiai",
      "paslauga"
    ],
    "has_video": false,
    "contact": "Tel. +370 63063352",
    "description": "Variklio diagnostika OBD — dirbame Telšiai ir apylinkėse. Profesionali įranga, sąskaitos faktūros. Skambinkite dėl laiko.",
    "provider_verified": true
  },
  {
    "id": "lt-svc-010",
    "seller_id": "seller-svc-2",
    "title": "Vėdinimo ir kondicionavimo aptarnavimas",
    "price": 60,
    "price_label": "nuo 60€",
    "location": "Jonava",
    "distance_km": 32.7,
    "image": "https://images.unsplash.com/photo-1581578731548-86083659925c?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "kondicionierius",
      "klimate",
      "paslauga",
      "jonava",
      "paslauga"
    ],
    "has_video": false,
    "contact": "Tel. +370 63071271",
    "description": "Siūlome vėdinimo ir kondicionavimo aptarnavimas Jonava regione. Greitas aptarnavimas, patyrę meistrai, garantija darbams.",
    "provider_verified": true
  },
  {
    "id": "lt-oth-001",
    "seller_id": "seller-oth-1",
    "title": "Kalnų dviratis 29\" ratais",
    "price": 380,
    "location": "Telšiai",
    "distance_km": 31,
    "image": "https://images.unsplash.com/photo-1485965120188-e430f974807a?w=800&h=600&fit=crop&auto=format",
    "category": "other",
    "tags": [
      "dviratis",
      "sportas",
      "laukas",
      "telšiai",
      "kita"
    ],
    "has_video": false,
    "contact": "Tel. +370 68000000",
    "description": "Parduodu kalnų dviratis 29\" ratais — Telšiai. Tvarkinga, veikianti, paruošta naudojimui."
  },
  {
    "id": "lt-oth-002",
    "seller_id": "seller-oth-2",
    "title": "Vaikiškas vežimėlis 3in1",
    "price": 220,
    "location": "Druskininkai",
    "distance_km": 32.3,
    "image": "https://images.unsplash.com/photo-1515488042361-ee00e3170fab?w=800&h=600&fit=crop&auto=format",
    "category": "other",
    "tags": [
      "vežimėlis",
      "vaikai",
      "kūdikis",
      "druskininkai",
      "kita"
    ],
    "has_video": false,
    "contact": "Tel. +370 68007919",
    "description": "Vaikiškas vežimėlis 3in1 iš Druskininkai. Gera būklė, sąžiningas pardavėjas. Galima apžiūrėti."
  },
  {
    "id": "lt-oth-003",
    "seller_id": "seller-oth-3",
    "title": "Bosch elektrinių įrankių komplektas",
    "price": 195,
    "location": "Šilutė",
    "distance_km": 33.6,
    "image": "https://images.unsplash.com/photo-1504141418495-c86464f4ed7c?w=800&h=600&fit=crop&auto=format",
    "category": "other",
    "tags": [
      "įrankiai",
      "bosch",
      "remontas",
      "šilutė",
      "kita"
    ],
    "has_video": false,
    "contact": "Tel. +370 68015838",
    "description": "Bosch elektrinių įrankių komplektas — Šilutė. Visi komplektai vietoje, be paslėptų defektų."
  },
  {
    "id": "lt-oth-004",
    "seller_id": "seller-oth-1",
    "title": "Universitetų vadovėlių rinkinys",
    "price": 45,
    "location": "Alytus",
    "distance_km": 34.9,
    "image": "https://images.unsplash.com/photo-1512820790802-52f98f7dc0b2?w=800&h=600&fit=crop&auto=format",
    "category": "other",
    "tags": [
      "knygos",
      "studijos",
      "vadovėliai",
      "alytus",
      "kita"
    ],
    "has_video": false,
    "contact": "Tel. +370 68023757",
    "description": "Pasiūlymas Alytus: Universitetų vadovėlių rinkinys. Skambinkite dėl detalių ir apžiūros laiko."
  },
  {
    "id": "lt-oth-005",
    "seller_id": "seller-oth-2",
    "title": "Sodo žoliapjovė + trimeris",
    "price": 160,
    "location": "Telšiai",
    "distance_km": 36.2,
    "image": "https://images.unsplash.com/photo-1416879595882-3373a0488b5b?w=800&h=600&fit=crop&auto=format",
    "category": "other",
    "tags": [
      "sodas",
      "technika",
      "žolė",
      "telšiai",
      "kita"
    ],
    "has_video": false,
    "contact": "Tel. +370 68031676",
    "description": "Parduodu sodo žoliapjovė + trimeris — Telšiai. Tvarkinga, veikianti, paruošta naudojimui."
  }
];
