import type { CategoryCapabilities, VerticalId } from "./types";

/** Fail-closed: unknown / unsupported categories get no privileged capabilities. */
export const FAIL_CLOSED_CAPABILITIES: CategoryCapabilities = {
  supportsOffers: false,
  supportsNegotiation: false,
  supportsPlatformPayment: false,
  supportsDeposit: false,
  supportsShipping: false,
  supportsPickup: false,
  supportsAppointments: false,
  supportsApplications: false,
  supportsMilestones: false,
  supportsDeliveryTracking: false,
  supportsReviews: false,
  supportsQuantity: false,
  supportsPrice: false,
  supportsRecurringService: false,
};

export const VERTICAL_CAPABILITIES: Record<VerticalId, CategoryCapabilities> = {
  TRANSPORT: {
    supportsOffers: true,
    supportsNegotiation: true,
    supportsPlatformPayment: true,
    supportsDeposit: true,
    supportsShipping: false,
    supportsPickup: true,
    supportsAppointments: true,
    supportsApplications: false,
    supportsMilestones: false,
    supportsDeliveryTracking: false,
    supportsReviews: true,
    supportsQuantity: false,
    supportsPrice: true,
    supportsRecurringService: false,
  },
  REAL_ESTATE: {
    supportsOffers: true,
    supportsNegotiation: true,
    supportsPlatformPayment: false,
    supportsDeposit: false,
    supportsShipping: false,
    supportsPickup: false,
    supportsAppointments: true,
    supportsApplications: false,
    supportsMilestones: false,
    supportsDeliveryTracking: false,
    supportsReviews: true,
    supportsQuantity: false,
    supportsPrice: true,
    supportsRecurringService: false,
  },
  ELECTRONICS: {
    supportsOffers: true,
    supportsNegotiation: true,
    supportsPlatformPayment: true,
    supportsDeposit: false,
    supportsShipping: true,
    supportsPickup: true,
    supportsAppointments: false,
    supportsApplications: false,
    supportsMilestones: false,
    supportsDeliveryTracking: true,
    supportsReviews: true,
    supportsQuantity: true,
    supportsPrice: true,
    supportsRecurringService: false,
  },
  SERVICES: {
    supportsOffers: true,
    supportsNegotiation: true,
    supportsPlatformPayment: true,
    supportsDeposit: false,
    supportsShipping: false,
    supportsPickup: false,
    supportsAppointments: true,
    supportsApplications: false,
    supportsMilestones: true,
    supportsDeliveryTracking: false,
    supportsReviews: true,
    supportsQuantity: false,
    supportsPrice: true,
    supportsRecurringService: true,
  },
  JOBS: {
    supportsOffers: false,
    supportsNegotiation: false,
    supportsPlatformPayment: false,
    supportsDeposit: false,
    supportsShipping: false,
    supportsPickup: false,
    supportsAppointments: true,
    supportsApplications: true,
    supportsMilestones: false,
    supportsDeliveryTracking: false,
    supportsReviews: true,
    supportsQuantity: false,
    supportsPrice: false,
    supportsRecurringService: false,
  },
  HOME_GARDEN: {
    supportsOffers: true,
    supportsNegotiation: true,
    supportsPlatformPayment: true,
    supportsDeposit: false,
    supportsShipping: true,
    supportsPickup: true,
    supportsAppointments: false,
    supportsApplications: false,
    supportsMilestones: false,
    supportsDeliveryTracking: true,
    supportsReviews: true,
    supportsQuantity: true,
    supportsPrice: true,
    supportsRecurringService: false,
  },
};
