/** Auto-generated by scripts/generate-mock-catalog.mjs — do not edit manually */
import type { LegacyListingInput } from "@/lib/types";

/** 108 realistic listings spread across Lithuania for demo, search and monetization QA. */
export const LITHUANIA_MOCK_CATALOG: LegacyListingInput[] = [
  {
    "id": "lt-auto-001",
    "title": "BMW 320d 2003",
    "price": 4250,
    "location": "Kaunas",
    "distanceKm": 1,
    "contact": "Tel. +370 61000000",
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "bmw",
      "320d",
      "automobilis",
      "dyzelinas",
      "kaunas"
    ],
    "description": "BMW 320d 2003 m. iš Kaunas. Rida 220 898 km, dyzelinas, mechaninė. Kėbulo būklė puiki, keli kosmetiniai pabraižymai. Techninė apžiūra galioja iki 2025-01. Be dūmų, be rūdžių. Parkavimo jutikliai priekyje ir gale. Serviso knygelė su visais įrašais.",
    "sellerId": "seller-auto-1",
    "createdAt": "2026-06-01T08:00:00.000Z",
    "attributes": {
      "make": "BMW",
      "model": "320d",
      "year": "2003",
      "mileage": "220 898 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Sedanas",
      "transmission": "Mechaninė",
      "taExpiry": "2025-01",
      "vin": "WBA0YWUSPMKHFDB97",
      "defects": "Smulkūs kosmetiniai defektai"
    },
    "vinVerified": false,
    "providerVerified": true,
    "visibilityTier": "top",
    "promoted": true
  },
  {
    "id": "lt-auto-002",
    "title": "BMW 320d Touring 2010",
    "price": 15000,
    "location": "Panevėžys",
    "distanceKm": 2.3,
    "contact": "Tel. +370 61007919",
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "bmw",
      "320d",
      "automobilis",
      "dyzelinas",
      "panevėžys"
    ],
    "description": "BMW 320d Touring 2010 m. iš Panevėžys. Rida 142 985 km, dyzelinas, automatinė. Be eismo įvykių, originali dažų spalva. Serviso knygelė su visais įrašais. Vienas savininkas Lietuvoje. Automatinis parkavimas. Du raktelių komplektas.",
    "sellerId": "seller-auto-2",
    "createdAt": "2026-06-02T09:13:00.000Z",
    "attributes": {
      "make": "BMW",
      "model": "320d Touring",
      "year": "2010",
      "mileage": "142 985 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Universalas",
      "transmission": "Automatinė",
      "taExpiry": "2026-02",
      "vin": "WBAHFDB97531ZXVTR",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-003",
    "title": "BMW 520d 2017",
    "price": 22000,
    "location": "Mažeikiai",
    "distanceKm": 3.6,
    "contact": "Tel. +370 61015838",
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "bmw",
      "520d",
      "automobilis",
      "dyzelinas",
      "mažeikiai"
    ],
    "description": "BMW 520d 2017 m. iš Mažeikiai. Rida 103 574 km, dyzelinas, automatinė su padėtimis. Priekinis buferis dažytas, techniškai tvarkinga. Du raktelių komplektas. Importuota iš Vokietijos, tvarkinga istorija. Xenon/LED priekiniai žibintai. Naujos vasarinės padangos.",
    "sellerId": "seller-auto-3",
    "createdAt": "2026-06-03T10:26:00.000Z",
    "attributes": {
      "make": "BMW",
      "model": "520d",
      "year": "2017",
      "mileage": "103 574 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Sedanas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2025-03",
      "vin": "WBA1ZXVTRNLJGECA8",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-004",
    "title": "BMW 530e 2024",
    "price": 29150,
    "location": "Kupiškis",
    "distanceKm": 4.9,
    "contact": "Tel. +370 61023757",
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "bmw",
      "530e",
      "automobilis",
      "plug-in hibridas",
      "kupiškis"
    ],
    "description": "BMW 530e 2024 m. iš Kupiškis. Rida 22 665 km, plug-in hibridas, mechaninė. Salonas labai tvarkingas, nerūkytas. Naujos vasarinės padangos. Neseniai atlikta didžioji TO. Start-stop sistema, mažos sąnaudos. Klimato kontrolė, šildomos sėdynės.",
    "sellerId": "seller-auto-4",
    "createdAt": "2026-06-04T11:39:00.000Z",
    "attributes": {
      "make": "BMW",
      "model": "530e",
      "year": "2024",
      "mileage": "22 665 km",
      "fuelType": "Plug-in hibridas",
      "bodyType": "Sedanas",
      "transmission": "Mechaninė",
      "taExpiry": "2026-04",
      "vin": "WBAJGECA86420YWUS",
      "defects": "Nėra"
    },
    "vinVerified": false,
    "providerVerified": false
  },
  {
    "id": "lt-auto-005",
    "title": "BMW X5 xDrive30d 2006",
    "price": 7400,
    "location": "Ukmergė",
    "distanceKm": 6.2,
    "contact": "Tel. +370 61031676",
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "bmw",
      "x5",
      "automobilis",
      "dyzelinas",
      "ukmergė"
    ],
    "description": "BMW X5 xDrive30d 2006 m. iš Ukmergė. Rida 245 793 km, dyzelinas, automatinė. Visi saugumo elementai veikia, paruošta registracijai. Klimato kontrolė, šildomos sėdynės. Nauja vairo traukė, stabdžių diskai. 4×4 visų ratų pavara. Navigacija, atbulinės kameros.",
    "sellerId": "seller-auto-5",
    "createdAt": "2026-06-05T12:52:00.000Z",
    "attributes": {
      "make": "BMW",
      "model": "X5 xDrive30d",
      "year": "2006",
      "mileage": "245 793 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Visureigis",
      "transmission": "Automatinė",
      "taExpiry": "2025-05",
      "vin": "WBA20YWUSPMKHFDB9",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-006",
    "title": "BMW 318i 2013",
    "price": 17750,
    "location": "Kėdainiai",
    "distanceKm": 7.5,
    "contact": "Tel. +370 61039595",
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "bmw",
      "318i",
      "automobilis",
      "benzinas",
      "kėdainiai"
    ],
    "description": "BMW 318i 2013 m. iš Kėdainiai. Rida 147 238 km, benzinas, automatinė su padėtimis. Kėbulo būklė puiki, keli kosmetiniai pabraižymai. Navigacija, atbulinės kameros. Odinis salonas, panoraminis stogas. Automatinė bagažinės dangtis. LED žibintai, lietaus jutiklis.",
    "sellerId": "seller-auto-6",
    "createdAt": "2026-06-06T13:05:00.000Z",
    "attributes": {
      "make": "BMW",
      "model": "318i",
      "year": "2013",
      "mileage": "147 238 km",
      "fuelType": "Benzinas",
      "bodyType": "Sedanas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2026-06",
      "vin": "WBAKHFDB97531ZXVT",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-007",
    "title": "Audi A4 Avant 2020",
    "price": 23950,
    "location": "Pasvalys",
    "distanceKm": 8.8,
    "contact": "Tel. +370 61047514",
    "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "audi",
      "a4",
      "automobilis",
      "dyzelinas",
      "pasvalys"
    ],
    "description": "Audi A4 Avant 2020 m. iš Pasvalys. Rida 80 465 km, dyzelinas, mechaninė. Be eismo įvykių, originali dažų spalva. LED žibintai, lietaus jutiklis. Apple CarPlay / Android Auto. Techninė apžiūra galioja iki 2025-07. Be dūmų, be rūdžių.",
    "sellerId": "seller-auto-7",
    "createdAt": "2026-06-07T14:18:00.000Z",
    "attributes": {
      "make": "Audi",
      "model": "A4 Avant",
      "year": "2020",
      "mileage": "80 465 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Universalas",
      "transmission": "Mechaninė",
      "taExpiry": "2025-07",
      "vin": "WBA31ZXVTRNLJGECA",
      "defects": "Nėra"
    },
    "vinVerified": false,
    "providerVerified": false
  },
  {
    "id": "lt-auto-008",
    "title": "Audi A4 2002",
    "price": 5550,
    "location": "Visaginas",
    "distanceKm": 10.1,
    "contact": "Tel. +370 61055433",
    "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "audi",
      "a4",
      "automobilis",
      "dyzelinas",
      "visaginas"
    ],
    "description": "Audi A4 2002 m. iš Visaginas. Rida 254 249 km, dyzelinas, automatinė. Priekinis buferis dažytas, techniškai tvarkinga. Be dūmų, be rūdžių. Parkavimo jutikliai priekyje ir gale. Serviso knygelė su visais įrašais. Vienas savininkas Lietuvoje.",
    "sellerId": "seller-auto-8",
    "createdAt": "2026-06-08T15:31:00.000Z",
    "attributes": {
      "make": "Audi",
      "model": "A4",
      "year": "2002",
      "mileage": "254 249 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Sedanas",
      "transmission": "Automatinė",
      "taExpiry": "2026-08",
      "vin": "WBALJGECA86420YWU",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": true,
    "visibilityTier": "plus"
  },
  {
    "id": "lt-auto-009",
    "title": "Audi A6 2009",
    "price": 12550,
    "location": "Radviliškis",
    "distanceKm": 11.4,
    "contact": "Tel. +370 61063352",
    "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "audi",
      "a6",
      "automobilis",
      "dyzelinas",
      "radviliškis"
    ],
    "description": "Audi A6 2009 m. iš Radviliškis. Rida 171 550 km, dyzelinas, automatinė su padėtimis. Salonas labai tvarkingas, nerūkytas. Vienas savininkas Lietuvoje. Automatinis parkavimas. Du raktelių komplektas. Importuota iš Vokietijos, tvarkinga istorija.",
    "sellerId": "seller-auto-9",
    "createdAt": "2026-06-09T16:44:00.000Z",
    "attributes": {
      "make": "Audi",
      "model": "A6",
      "year": "2009",
      "mileage": "171 550 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Sedanas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2025-09",
      "vin": "WBA420YWUSPMKHFDB",
      "defects": "Smulkūs kosmetiniai defektai"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-010",
    "title": "Audi Q5 2016",
    "price": 19900,
    "location": "Kaunas",
    "distanceKm": 12.7,
    "contact": "Tel. +370 61071271",
    "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "audi",
      "q5",
      "automobilis",
      "dyzelinas",
      "kaunas"
    ],
    "description": "Audi Q5 2016 m. iš Kaunas. Rida 87 353 km, dyzelinas, mechaninė. Visi saugumo elementai veikia, paruošta registracijai. Importuota iš Vokietijos, tvarkinga istorija. Xenon/LED priekiniai žibintai. Naujos vasarinės padangos. Neseniai atlikta didžioji TO.",
    "sellerId": "seller-auto-10",
    "createdAt": "2026-06-10T17:57:00.000Z",
    "attributes": {
      "make": "Audi",
      "model": "Q5",
      "year": "2016",
      "mileage": "87 353 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Visureigis",
      "transmission": "Mechaninė",
      "taExpiry": "2026-10",
      "vin": "WBAMKHFDB97531ZXV",
      "defects": "Nėra"
    },
    "vinVerified": false,
    "providerVerified": false
  },
  {
    "id": "lt-auto-011",
    "title": "Audi A3 Sportback 2023",
    "price": 26700,
    "location": "Panevėžys",
    "distanceKm": 11,
    "contact": "Tel. +370 61079190",
    "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "audi",
      "a3",
      "automobilis",
      "benzinas",
      "panevėžys"
    ],
    "description": "Audi A3 Sportback 2023 m. iš Panevėžys. Rida 41 658 km, benzinas, automatinė. Kėbulo būklė puiki, keli kosmetiniai pabraižymai. Neseniai atlikta didžioji TO. Start-stop sistema, mažos sąnaudos. Klimato kontrolė, šildomos sėdynės. Nauja vairo traukė, stabdžių diskai.",
    "sellerId": "seller-auto-11",
    "createdAt": "2026-06-11T08:10:00.000Z",
    "attributes": {
      "make": "Audi",
      "model": "A3 Sportback",
      "year": "2023",
      "mileage": "41 658 km",
      "fuelType": "Benzinas",
      "bodyType": "Hečbekas",
      "transmission": "Automatinė",
      "taExpiry": "2025-11",
      "vin": "WBA531ZXVTRNLJGEC",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-012",
    "title": "Volkswagen Golf 2005",
    "price": 8200,
    "location": "Mažeikiai",
    "distanceKm": 12.3,
    "contact": "Tel. +370 61087109",
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volkswagen",
      "golf",
      "automobilis",
      "dyzelinas",
      "mažeikiai"
    ],
    "description": "Volkswagen Golf 2005 m. iš Mažeikiai. Rida 184 950 km, dyzelinas, automatinė su padėtimis. Be eismo įvykių, originali dažų spalva. Nauja vairo traukė, stabdžių diskai. 4×4 visų ratų pavara. Navigacija, atbulinės kameros. Odinis salonas, panoraminis stogas.",
    "sellerId": "seller-auto-12",
    "createdAt": "2026-06-12T09:23:00.000Z",
    "attributes": {
      "make": "Volkswagen",
      "model": "Golf",
      "year": "2005",
      "mileage": "184 950 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Hečbekas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2026-12",
      "vin": "WBANLJGECA86420YW",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-013",
    "title": "Volkswagen Passat 2012",
    "price": 15250,
    "location": "Kupiškis",
    "distanceKm": 13.6,
    "contact": "Tel. +370 61095028",
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volkswagen",
      "passat",
      "automobilis",
      "dyzelinas",
      "kupiškis"
    ],
    "description": "Volkswagen Passat 2012 m. iš Kupiškis. Rida 116 609 km, dyzelinas, mechaninė. Priekinis buferis dažytas, techniškai tvarkinga. Odinis salonas, panoraminis stogas. Automatinė bagažinės dangtis. LED žibintai, lietaus jutiklis. Apple CarPlay / Android Auto.",
    "sellerId": "seller-auto-1",
    "createdAt": "2026-06-13T10:36:00.000Z",
    "attributes": {
      "make": "Volkswagen",
      "model": "Passat",
      "year": "2012",
      "mileage": "116 609 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Universalas",
      "transmission": "Mechaninė",
      "taExpiry": "2025-01",
      "vin": "WBA6420YWUSPMKHFD",
      "defects": "Nėra"
    },
    "vinVerified": false,
    "providerVerified": false
  },
  {
    "id": "lt-auto-014",
    "title": "Volkswagen Tiguan 2019",
    "price": 22650,
    "location": "Ukmergė",
    "distanceKm": 14.9,
    "contact": "Tel. +370 61102947",
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volkswagen",
      "tiguan",
      "automobilis",
      "dyzelinas",
      "ukmergė"
    ],
    "description": "Volkswagen Tiguan 2019 m. iš Ukmergė. Rida 46 770 km, dyzelinas, automatinė. Salonas labai tvarkingas, nerūkytas. Apple CarPlay / Android Auto. Techninė apžiūra galioja iki 2026-02. Be dūmų, be rūdžių. Parkavimo jutikliai priekyje ir gale.",
    "sellerId": "seller-auto-2",
    "createdAt": "2026-06-14T11:49:00.000Z",
    "attributes": {
      "make": "Volkswagen",
      "model": "Tiguan",
      "year": "2019",
      "mileage": "46 770 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Visureigis",
      "transmission": "Automatinė",
      "taExpiry": "2026-02",
      "vin": "WBAPMKHFDB97531ZX",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-015",
    "title": "Volkswagen Touran 2001",
    "price": 1750,
    "location": "Kėdainiai",
    "distanceKm": 16.2,
    "contact": "Tel. +370 61110866",
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volkswagen",
      "touran",
      "automobilis",
      "dyzelinas",
      "kėdainiai"
    ],
    "description": "Volkswagen Touran 2001 m. iš Kėdainiai. Rida 256 158 km, dyzelinas, automatinė su padėtimis. Visi saugumo elementai veikia, paruošta registracijai. Parkavimo jutikliai priekyje ir gale. Serviso knygelė su visais įrašais. Vienas savininkas Lietuvoje. Automatinis parkavimas.",
    "sellerId": "seller-auto-3",
    "createdAt": "2026-06-15T12:02:00.000Z",
    "attributes": {
      "make": "Volkswagen",
      "model": "Touran",
      "year": "2001",
      "mileage": "256 158 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Universalas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2025-03",
      "vin": "WBA7531ZXVTRNLJGE",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": true
  },
  {
    "id": "lt-auto-016",
    "title": "Volvo V70 2008",
    "price": 11050,
    "location": "Pasvalys",
    "distanceKm": 17.5,
    "contact": "Tel. +370 61118785",
    "image": "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volvo",
      "v70",
      "automobilis",
      "dyzelinas",
      "pasvalys"
    ],
    "description": "Volvo V70 2008 m. iš Pasvalys. Rida 208 233 km, dyzelinas, mechaninė. Kėbulo būklė puiki, keli kosmetiniai pabraižymai. Automatinis parkavimas. Du raktelių komplektas. Importuota iš Vokietijos, tvarkinga istorija. Xenon/LED priekiniai žibintai.",
    "sellerId": "seller-auto-4",
    "createdAt": "2026-06-16T13:15:00.000Z",
    "attributes": {
      "make": "Volvo",
      "model": "V70",
      "year": "2008",
      "mileage": "208 233 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Universalas",
      "transmission": "Mechaninė",
      "taExpiry": "2026-04",
      "vin": "WBARNLJGECA86420Y",
      "defects": "Nėra"
    },
    "vinVerified": false,
    "providerVerified": false
  },
  {
    "id": "lt-auto-017",
    "title": "Volvo XC60 2015",
    "price": 19600,
    "location": "Visaginas",
    "distanceKm": 18.8,
    "contact": "Tel. +370 61126704",
    "image": "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volvo",
      "xc60",
      "automobilis",
      "dyzelinas",
      "visaginas"
    ],
    "description": "Volvo XC60 2015 m. iš Visaginas. Rida 119 250 km, dyzelinas, automatinė. Be eismo įvykių, originali dažų spalva. Xenon/LED priekiniai žibintai. Naujos vasarinės padangos. Neseniai atlikta didžioji TO. Start-stop sistema, mažos sąnaudos.",
    "sellerId": "seller-auto-5",
    "createdAt": "2026-06-17T14:28:00.000Z",
    "attributes": {
      "make": "Volvo",
      "model": "XC60",
      "year": "2015",
      "mileage": "119 250 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Visureigis",
      "transmission": "Automatinė",
      "taExpiry": "2025-05",
      "vin": "WBA86420YWUSPMKHF",
      "defects": "Smulkūs kosmetiniai defektai"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-018",
    "title": "Volvo XC90 2022",
    "price": 35000,
    "location": "Radviliškis",
    "distanceKm": 20.1,
    "contact": "Tel. +370 61134623",
    "image": "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volvo",
      "xc90",
      "automobilis",
      "dyzelinas",
      "radviliškis"
    ],
    "description": "Volvo XC90 2022 m. iš Radviliškis. Rida 28 769 km, dyzelinas, automatinė su padėtimis. Priekinis buferis dažytas, techniškai tvarkinga. Start-stop sistema, mažos sąnaudos. Klimato kontrolė, šildomos sėdynės. Nauja vairo traukė, stabdžių diskai. 4×4 visų ratų pavara.",
    "sellerId": "seller-auto-6",
    "createdAt": "2026-06-18T15:41:00.000Z",
    "attributes": {
      "make": "Volvo",
      "model": "XC90",
      "year": "2022",
      "mileage": "28 769 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Visureigis",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2026-06",
      "vin": "WBASPMKHFDB97531Z",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-019",
    "title": "Volvo S60 2004",
    "price": 2800,
    "location": "Kaunas",
    "distanceKm": 21.4,
    "contact": "Tel. +370 61142542",
    "image": "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "volvo",
      "s60",
      "automobilis",
      "benzinas",
      "kaunas"
    ],
    "description": "Volvo S60 2004 m. iš Kaunas. Rida 182 225 km, benzinas, mechaninė. Salonas labai tvarkingas, nerūkytas. 4×4 visų ratų pavara. Navigacija, atbulinės kameros. Odinis salonas, panoraminis stogas. Automatinė bagažinės dangtis.",
    "sellerId": "seller-auto-7",
    "createdAt": "2026-06-19T16:54:00.000Z",
    "attributes": {
      "make": "Volvo",
      "model": "S60",
      "year": "2004",
      "mileage": "182 225 km",
      "fuelType": "Benzinas",
      "bodyType": "Sedanas",
      "transmission": "Mechaninė",
      "taExpiry": "2025-07",
      "vin": "WBA97531ZXVTRNLJG",
      "defects": "Nėra"
    },
    "vinVerified": false,
    "providerVerified": false
  },
  {
    "id": "lt-auto-020",
    "title": "Toyota Corolla 2011",
    "price": 15000,
    "location": "Panevėžys",
    "distanceKm": 22.7,
    "contact": "Tel. +370 61150461",
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "toyota",
      "corolla",
      "automobilis",
      "hibridas",
      "panevėžys"
    ],
    "description": "Toyota Corolla 2011 m. iš Panevėžys. Rida 149 098 km, hibridas, automatinė. Visi saugumo elementai veikia, paruošta registracijai. Automatinė bagažinės dangtis. LED žibintai, lietaus jutiklis. Apple CarPlay / Android Auto. Techninė apžiūra galioja iki 2026-08.",
    "sellerId": "seller-auto-8",
    "createdAt": "2026-06-20T17:07:00.000Z",
    "attributes": {
      "make": "Toyota",
      "model": "Corolla",
      "year": "2011",
      "mileage": "149 098 km",
      "fuelType": "Hibridas",
      "bodyType": "Hečbekas",
      "transmission": "Automatinė",
      "taExpiry": "2026-08",
      "vin": "WBATRNLJGECA86420",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-021",
    "title": "Toyota Avensis 2018",
    "price": 20750,
    "location": "Mažeikiai",
    "distanceKm": 21,
    "contact": "Tel. +370 61158380",
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "toyota",
      "avensis",
      "automobilis",
      "dyzelinas",
      "mažeikiai"
    ],
    "description": "Toyota Avensis 2018 m. iš Mažeikiai. Rida 74 473 km, dyzelinas, automatinė su padėtimis. Kėbulo būklė puiki, keli kosmetiniai pabraižymai. Techninė apžiūra galioja iki 2027-09. Be dūmų, be rūdžių. Parkavimo jutikliai priekyje ir gale. Serviso knygelė su visais įrašais.",
    "sellerId": "seller-auto-9",
    "createdAt": "2026-06-21T08:20:00.000Z",
    "attributes": {
      "make": "Toyota",
      "model": "Avensis",
      "year": "2018",
      "mileage": "74 473 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Universalas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2025-09",
      "vin": "WBAA86420YWUSPMKH",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-022",
    "title": "Toyota RAV4 2000",
    "price": 3100,
    "location": "Kupiškis",
    "distanceKm": 22.3,
    "contact": "Tel. +370 61166299",
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "toyota",
      "rav4",
      "automobilis",
      "hibridas",
      "kupiškis"
    ],
    "description": "Toyota RAV4 2000 m. iš Kupiškis. Rida 257 305 km, hibridas, mechaninė. Be eismo įvykių, originali dažų spalva. Serviso knygelė su visais įrašais. Vienas savininkas Lietuvoje. Automatinis parkavimas. Du raktelių komplektas.",
    "sellerId": "seller-auto-10",
    "createdAt": "2026-06-22T09:33:00.000Z",
    "attributes": {
      "make": "Toyota",
      "model": "RAV4",
      "year": "2000",
      "mileage": "257 305 km",
      "fuelType": "Hibridas",
      "bodyType": "Visureigis",
      "transmission": "Mechaninė",
      "taExpiry": "2026-10",
      "vin": "WBAUSPMKHFDB97531",
      "defects": "Nėra"
    },
    "vinVerified": false,
    "providerVerified": true
  },
  {
    "id": "lt-auto-023",
    "title": "Toyota Yaris 2007",
    "price": 12700,
    "location": "Ukmergė",
    "distanceKm": 23.6,
    "contact": "Tel. +370 61174218",
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "toyota",
      "yaris",
      "automobilis",
      "benzinas",
      "ukmergė"
    ],
    "description": "Toyota Yaris 2007 m. iš Ukmergė. Rida 206 314 km, benzinas, automatinė. Priekinis buferis dažytas, techniškai tvarkinga. Du raktelių komplektas. Importuota iš Vokietijos, tvarkinga istorija. Xenon/LED priekiniai žibintai. Naujos vasarinės padangos.",
    "sellerId": "seller-auto-11",
    "createdAt": "2026-06-23T10:46:00.000Z",
    "attributes": {
      "make": "Toyota",
      "model": "Yaris",
      "year": "2007",
      "mileage": "206 314 km",
      "fuelType": "Benzinas",
      "bodyType": "Hečbekas",
      "transmission": "Automatinė",
      "taExpiry": "2025-11",
      "vin": "WBAB97531ZXVTRNLJ",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-auto-024",
    "title": "Mercedes-Benz C220 d 2014",
    "price": 19950,
    "location": "Kėdainiai",
    "distanceKm": 24.9,
    "contact": "Tel. +370 61182137",
    "image": "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "mercedes-benz",
      "c220",
      "automobilis",
      "dyzelinas",
      "kėdainiai"
    ],
    "description": "Mercedes-Benz C220 d 2014 m. iš Kėdainiai. Rida 152 545 km, dyzelinas, automatinė su padėtimis. Salonas labai tvarkingas, nerūkytas. Naujos vasarinės padangos. Neseniai atlikta didžioji TO. Start-stop sistema, mažos sąnaudos. Klimato kontrolė, šildomos sėdynės.",
    "sellerId": "seller-auto-12",
    "createdAt": "2026-06-24T11:59:00.000Z",
    "attributes": {
      "make": "Mercedes-Benz",
      "model": "C220 d",
      "year": "2014",
      "mileage": "152 545 km",
      "fuelType": "Dyzelinas",
      "bodyType": "Sedanas",
      "transmission": "Automatinė su padėtimis",
      "taExpiry": "2026-12",
      "vin": "WBAVTRNLJGECA8642",
      "defects": "Nėra"
    },
    "vinVerified": true,
    "providerVerified": false
  },
  {
    "id": "lt-nt-001",
    "title": "2 kambarių butas su balkonu",
    "price": 145000,
    "location": "Alytus",
    "distanceKm": 11,
    "contact": "Tel. +370 64000000",
    "image": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "butas",
      "nt",
      "nuomai",
      "alytus",
      "nekilnojamasis"
    ],
    "description": "2 kambarių butas su balkonu — Alytus. Plotas 54 m², 2 kamb. Butas. Puiki vieta, šalia infrastruktūra, transportas.",
    "sellerId": "seller-nt-1",
    "createdAt": "2026-06-04T11:00:00.000Z",
    "attributes": {
      "propertyType": "Butas",
      "rooms": "2",
      "area": "54 m²"
    },
    "visibilityTier": "top"
  },
  {
    "id": "lt-nt-002",
    "title": "3 kambarių butas naujame name",
    "price": 198000,
    "location": "Mažeikiai",
    "distanceKm": 12.3,
    "contact": "Tel. +370 64007919",
    "image": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "butas",
      "nt",
      "naujas",
      "mažeikiai",
      "nekilnojamasis"
    ],
    "description": "Parduodamas butas Mažeikiai mieste. 3 kamb., 72 m². Tvarkinga būklė, galima apžiūrėti sutartu laiku.",
    "sellerId": "seller-nt-2",
    "createdAt": "2026-06-05T11:05:00.000Z",
    "attributes": {
      "propertyType": "Butas",
      "rooms": "3",
      "area": "72 m²"
    }
  },
  {
    "id": "lt-nt-003",
    "title": "Šiuolaikiškas loftas centre",
    "price": 235000,
    "location": "Utena",
    "distanceKm": 13.6,
    "contact": "Tel. +370 64015838",
    "image": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "loftas",
      "nt",
      "centras",
      "utena",
      "nekilnojamasis"
    ],
    "description": "Šiuolaikiškas loftas centre Utena rajone. 68 m², Butas. Skaidri dokumentacija, padėsime su paskola.",
    "sellerId": "seller-nt-3",
    "createdAt": "2026-06-06T11:10:00.000Z",
    "attributes": {
      "propertyType": "Butas",
      "rooms": "2",
      "area": "68 m²"
    }
  },
  {
    "id": "lt-nt-004",
    "title": "1 kambario butas studentams",
    "price": 89000,
    "location": "Telšiai",
    "distanceKm": 14.9,
    "contact": "Tel. +370 64023757",
    "image": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "butas",
      "nt",
      "nuomai",
      "telšiai",
      "nekilnojamasis"
    ],
    "description": "NT pasiūlymas Telšiai: 1 kambario butas studentams. 1 kamb., 32 m². Tinka gyvenimui ar investicijai.",
    "sellerId": "seller-nt-4",
    "createdAt": "2026-06-07T11:15:00.000Z",
    "attributes": {
      "propertyType": "Butas",
      "rooms": "1",
      "area": "32 m²"
    }
  },
  {
    "id": "lt-nt-005",
    "title": "Individualus namas su garažu",
    "price": 285000,
    "location": "Ukmergė",
    "distanceKm": 16.2,
    "contact": "Tel. +370 64031676",
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "namas",
      "nt",
      "sklypas",
      "ukmergė",
      "nekilnojamasis"
    ],
    "description": "Individualus namas su garažu — Ukmergė. Plotas 145 m², 4 kamb. Namas. Puiki vieta, šalia infrastruktūra, transportas.",
    "sellerId": "seller-nt-5",
    "createdAt": "2026-06-08T11:20:00.000Z",
    "attributes": {
      "propertyType": "Namas",
      "rooms": "4",
      "area": "145 m²"
    },
    "visibilityTier": "plus"
  },
  {
    "id": "lt-nt-006",
    "title": "Namas Priemiestyje su terasa",
    "price": 320000,
    "location": "Jonava",
    "distanceKm": 17.5,
    "contact": "Tel. +370 64039595",
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "namas",
      "nt",
      "terasa",
      "jonava",
      "nekilnojamasis"
    ],
    "description": "Parduodamas namas Jonava mieste. 5 kamb., 168 m². Tvarkinga būklė, galima apžiūrėti sutartu laiku.",
    "sellerId": "seller-nt-6",
    "createdAt": "2026-06-09T11:25:00.000Z",
    "attributes": {
      "propertyType": "Namas",
      "rooms": "5",
      "area": "168 m²"
    }
  },
  {
    "id": "lt-nt-007",
    "title": "Kotedžas dviems šeimoms",
    "price": 265000,
    "location": "Druskininkai",
    "distanceKm": 18.8,
    "contact": "Tel. +370 64047514",
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "kotedžas",
      "nt",
      "druskininkai",
      "nekilnojamasis"
    ],
    "description": "Kotedžas dviems šeimoms Druskininkai rajone. 190 m², Namas. Skaidri dokumentacija, padėsime su paskola.",
    "sellerId": "seller-nt-1",
    "createdAt": "2026-06-10T11:30:00.000Z",
    "attributes": {
      "propertyType": "Namas",
      "rooms": "6",
      "area": "190 m²"
    }
  },
  {
    "id": "lt-nt-008",
    "title": "Sklypas statybai 12 a",
    "price": 42000,
    "location": "Pasvalys",
    "distanceKm": 20.1,
    "contact": "Tel. +370 64055433",
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "sklypas",
      "nt",
      "statyba",
      "pasvalys",
      "nekilnojamasis"
    ],
    "description": "NT pasiūlymas Pasvalys: Sklypas statybai 12 a. — kamb., 12 a. Tinka gyvenimui ar investicijai.",
    "sellerId": "seller-nt-2",
    "createdAt": "2026-06-11T11:35:00.000Z",
    "attributes": {
      "propertyType": "Sklypas",
      "rooms": "—",
      "area": "12 a"
    }
  },
  {
    "id": "lt-nt-009",
    "title": "Komercinės patalpos centre",
    "price": 175000,
    "location": "Kretinga",
    "distanceKm": 21.4,
    "contact": "Tel. +370 64063352",
    "image": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "komercinis",
      "nt",
      "biuras",
      "kretinga",
      "nekilnojamasis"
    ],
    "description": "Komercinės patalpos centre — Kretinga. Plotas 110 m², — kamb. Komercinis. Puiki vieta, šalia infrastruktūra, transportas.",
    "sellerId": "seller-nt-3",
    "createdAt": "2026-06-12T11:40:00.000Z",
    "attributes": {
      "propertyType": "Komercinis",
      "rooms": "—",
      "area": "110 m²"
    }
  },
  {
    "id": "lt-nt-010",
    "title": "Butas nuomai — įrengtas",
    "price": 650,
    "priceLabel": "650€/mėn.",
    "location": "Šilutė",
    "distanceKm": 22.7,
    "contact": "Tel. +370 64071271",
    "image": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "nuoma",
      "nt",
      "butas",
      "šilutė",
      "nekilnojamasis"
    ],
    "description": "Parduodamas nuoma Šilutė mieste. 2 kamb., 48 m². Tvarkinga būklė, galima apžiūrėti sutartu laiku.",
    "sellerId": "seller-nt-4",
    "createdAt": "2026-06-13T11:45:00.000Z",
    "attributes": {
      "propertyType": "Nuoma",
      "rooms": "2",
      "area": "48 m²"
    }
  },
  {
    "id": "lt-nt-011",
    "title": "Kambarys bendrame bute",
    "price": 220,
    "priceLabel": "220€/mėn.",
    "location": "Radviliškis",
    "distanceKm": 21,
    "contact": "Tel. +370 64079190",
    "image": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "nuoma",
      "kambarys",
      "nt",
      "radviliškis",
      "nekilnojamasis"
    ],
    "description": "Kambarys bendrame bute Radviliškis rajone. 14 m², Nuoma. Skaidri dokumentacija, padėsime su paskola.",
    "sellerId": "seller-nt-5",
    "createdAt": "2026-06-14T11:50:00.000Z",
    "attributes": {
      "propertyType": "Nuoma",
      "rooms": "1",
      "area": "14 m²"
    }
  },
  {
    "id": "lt-nt-012",
    "title": "Sodyba su pirtimi ir sodu",
    "price": 155000,
    "location": "Vilnius",
    "distanceKm": 22.3,
    "contact": "Tel. +370 64087109",
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "sodyba",
      "nt",
      "pirtis",
      "vilnius",
      "nekilnojamasis"
    ],
    "description": "NT pasiūlymas Vilnius: Sodyba su pirtimi ir sodu. 3 kamb., 95 m². Tinka gyvenimui ar investicijai.",
    "sellerId": "seller-nt-6",
    "createdAt": "2026-06-15T11:55:00.000Z",
    "attributes": {
      "propertyType": "Namas",
      "rooms": "3",
      "area": "95 m²"
    }
  },
  {
    "id": "lt-nt-013",
    "title": "4 kambarių butas su parkingu",
    "price": 215000,
    "location": "Klaipėda",
    "distanceKm": 23.6,
    "contact": "Tel. +370 64095028",
    "image": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "butas",
      "nt",
      "parkingas",
      "klaipėda",
      "nekilnojamasis"
    ],
    "description": "4 kambarių butas su parkingu — Klaipėda. Plotas 88 m², 4 kamb. Butas. Puiki vieta, šalia infrastruktūra, transportas.",
    "sellerId": "seller-nt-1",
    "createdAt": "2026-06-16T12:00:00.000Z",
    "attributes": {
      "propertyType": "Butas",
      "rooms": "4",
      "area": "88 m²"
    }
  },
  {
    "id": "lt-nt-014",
    "title": "Žemės sklypas ūkio paskirčiai",
    "price": 28000,
    "location": "Panevėžys",
    "distanceKm": 24.9,
    "contact": "Tel. +370 64102947",
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "žemė",
      "nt",
      "sklypas",
      "panevėžys",
      "nekilnojamasis"
    ],
    "description": "Parduodamas sklypas Panevėžys mieste. — kamb., 30 a. Tvarkinga būklė, galima apžiūrėti sutartu laiku.",
    "sellerId": "seller-nt-2",
    "createdAt": "2026-06-17T12:05:00.000Z",
    "attributes": {
      "propertyType": "Sklypas",
      "rooms": "—",
      "area": "30 a"
    }
  },
  {
    "id": "lt-job-001",
    "title": "Vairuotojas CE — tarptautiniai reisai",
    "price": 0,
    "priceLabel": "nuo 1800€/mėn.",
    "location": "Mažeikiai",
    "distanceKm": 21,
    "contact": "Tel. +370 65000000",
    "image": "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "vairuotojas",
      "darbas",
      "ce",
      "mažeikiai",
      "karjera"
    ],
    "description": "Vairuotojas CE — tarptautiniai reisai — Mažeikiai ir apylinkės. Etatas: Pamainos. Patirtis: 2+ m..",
    "sellerId": "seller-job-1",
    "createdAt": "2026-06-06T09:00:00.000Z",
    "attributes": {
      "position": "Vairuotojas",
      "schedule": "Pamainos",
      "experience": "2+ m."
    }
  },
  {
    "id": "lt-job-002",
    "title": "Sandėlininkas — naktinės pamainos",
    "price": 0,
    "priceLabel": "nuo 1200€/mėn.",
    "location": "Kupiškis",
    "distanceKm": 22.3,
    "contact": "Tel. +370 65007919",
    "image": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "sandėlis",
      "darbas",
      "logistika",
      "kupiškis",
      "karjera"
    ],
    "description": "Ieškome Sandėlininkas Kupiškis. nuo 1200€/mėn.. Suteikiame apmokymą.",
    "sellerId": "seller-job-2",
    "createdAt": "2026-06-07T09:09:00.000Z",
    "attributes": {
      "position": "Sandėlininkas",
      "schedule": "Naktinis",
      "experience": "Be patirties"
    }
  },
  {
    "id": "lt-job-003",
    "title": "PHP programuotojas (Symfony)",
    "price": 0,
    "priceLabel": "2500–4000€/mėn.",
    "location": "Ukmergė",
    "distanceKm": 23.6,
    "contact": "Tel. +370 65015838",
    "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "programuotojas",
      "it",
      "darbas",
      "ukmergė",
      "karjera"
    ],
    "description": "Darbo pasiūlymas: PHP programuotojas (Symfony). Vieta: Ukmergė. Grafikas: Hibridas. Kreipkitės su CV.",
    "sellerId": "seller-job-3",
    "createdAt": "2026-06-08T09:18:00.000Z",
    "attributes": {
      "position": "Programuotojas",
      "schedule": "Hibridas",
      "experience": "3+ m."
    },
    "visibilityTier": "plus"
  },
  {
    "id": "lt-job-004",
    "title": "Virėjas — restoranas centre",
    "price": 0,
    "priceLabel": "nuo 1400€/mėn.",
    "location": "Kėdainiai",
    "distanceKm": 24.9,
    "contact": "Tel. +370 65023757",
    "image": "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "virėjas",
      "maistas",
      "darbas",
      "kėdainiai",
      "karjera"
    ],
    "description": "Virėjas pozicija Kėdainiai. Virėjas — restoranas centre. Oficialus įdarbinimas, socialinės garantijos.",
    "sellerId": "seller-job-4",
    "createdAt": "2026-06-09T09:27:00.000Z",
    "attributes": {
      "position": "Virėjas",
      "schedule": "Pilnas etatas",
      "experience": "1+ m."
    }
  },
  {
    "id": "lt-job-005",
    "title": "Medicinos seselė — slaugos skyrius",
    "price": 0,
    "priceLabel": "nuo 1600€/mėn.",
    "location": "Pasvalys",
    "distanceKm": 26.2,
    "contact": "Tel. +370 65031676",
    "image": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "slauga",
      "medicina",
      "darbas",
      "pasvalys",
      "karjera"
    ],
    "description": "Medicinos seselė — slaugos skyrius — Pasvalys ir apylinkės. Etatas: Pamainos. Patirtis: 2+ m..",
    "sellerId": "seller-job-5",
    "createdAt": "2026-06-10T09:36:00.000Z",
    "attributes": {
      "position": "Seselė",
      "schedule": "Pamainos",
      "experience": "2+ m."
    }
  },
  {
    "id": "lt-job-006",
    "title": "Statybų darbų vadovas",
    "price": 0,
    "priceLabel": "nuo 2200€/mėn.",
    "location": "Visaginas",
    "distanceKm": 27.5,
    "contact": "Tel. +370 65039595",
    "image": "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "statyba",
      "vadovas",
      "darbas",
      "visaginas",
      "karjera"
    ],
    "description": "Ieškome Vadovas Visaginas. nuo 2200€/mėn.. Suteikiame apmokymą.",
    "sellerId": "seller-job-1",
    "createdAt": "2026-06-11T09:45:00.000Z",
    "attributes": {
      "position": "Vadovas",
      "schedule": "Pilnas etatas",
      "experience": "5+ m."
    }
  },
  {
    "id": "lt-job-007",
    "title": "Pardavėjas-consultant elektronikos salėje",
    "price": 0,
    "priceLabel": "nuo 1100€/mėn.",
    "location": "Radviliškis",
    "distanceKm": 28.8,
    "contact": "Tel. +370 65047514",
    "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "pardavimas",
      "darbas",
      "retail",
      "radviliškis",
      "karjera"
    ],
    "description": "Darbo pasiūlymas: Pardavėjas-consultant elektronikos salėje. Vieta: Radviliškis. Grafikas: Pamainos. Kreipkitės su CV.",
    "sellerId": "seller-job-2",
    "createdAt": "2026-06-12T09:54:00.000Z",
    "attributes": {
      "position": "Pardavėjas",
      "schedule": "Pamainos",
      "experience": "Be patirties"
    }
  },
  {
    "id": "lt-job-008",
    "title": "Buhalterė — maža įmonė",
    "price": 0,
    "priceLabel": "nuo 1500€/mėn.",
    "location": "Kaunas",
    "distanceKm": 30.1,
    "contact": "Tel. +370 65055433",
    "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "buhalterija",
      "darbas",
      "finansai",
      "kaunas",
      "karjera"
    ],
    "description": "Buhalterė pozicija Kaunas. Buhalterė — maža įmonė. Oficialus įdarbinimas, socialinės garantijos.",
    "sellerId": "seller-job-3",
    "createdAt": "2026-06-13T10:03:00.000Z",
    "attributes": {
      "position": "Buhalterė",
      "schedule": "Pilnas etatas",
      "experience": "3+ m."
    }
  },
  {
    "id": "lt-job-009",
    "title": "Kurjeris — nuosavas automobilis",
    "price": 0,
    "priceLabel": "nuo 1000€/mėn.",
    "location": "Panevėžys",
    "distanceKm": 31.4,
    "contact": "Tel. +370 65063352",
    "image": "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "kurjeris",
      "logistika",
      "darbas",
      "panevėžys",
      "karjera"
    ],
    "description": "Kurjeris — nuosavas automobilis — Panevėžys ir apylinkės. Etatas: Lankstus. Patirtis: Be patirties.",
    "sellerId": "seller-job-4",
    "createdAt": "2026-06-14T10:12:00.000Z",
    "attributes": {
      "position": "Kurjeris",
      "schedule": "Lankstus",
      "experience": "Be patirties"
    }
  },
  {
    "id": "lt-job-010",
    "title": "Suvirintojas TIG/MIG",
    "price": 0,
    "priceLabel": "nuo 1700€/mėn.",
    "location": "Mažeikiai",
    "distanceKm": 32.7,
    "contact": "Tel. +370 65071271",
    "image": "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "suvirintojas",
      "gamykla",
      "darbas",
      "mažeikiai",
      "karjera"
    ],
    "description": "Ieškome Suvirintojas Mažeikiai. nuo 1700€/mėn.. Suteikiame apmokymą.",
    "sellerId": "seller-job-5",
    "createdAt": "2026-06-15T10:21:00.000Z",
    "attributes": {
      "position": "Suvirintojas",
      "schedule": "Pamainos",
      "experience": "2+ m."
    }
  },
  {
    "id": "lt-job-011",
    "title": "Klientų aptarnavimo specialistas",
    "price": 0,
    "priceLabel": "nuo 1150€/mėn.",
    "location": "Kupiškis",
    "distanceKm": 31,
    "contact": "Tel. +370 65079190",
    "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "support",
      "darbas",
      "biuras",
      "kupiškis",
      "karjera"
    ],
    "description": "Darbo pasiūlymas: Klientų aptarnavimo specialistas. Vieta: Kupiškis. Grafikas: Pamainos. Kreipkitės su CV.",
    "sellerId": "seller-job-1",
    "createdAt": "2026-06-16T10:30:00.000Z",
    "attributes": {
      "position": "Specialistas",
      "schedule": "Pamainos",
      "experience": "1+ m."
    }
  },
  {
    "id": "lt-job-012",
    "title": "Auklė / babysitter — nuolatinė",
    "price": 0,
    "priceLabel": "nuo 900€/mėn.",
    "location": "Ukmergė",
    "distanceKm": 32.3,
    "contact": "Tel. +370 65087109",
    "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "auklė",
      "darbas",
      "vaikai",
      "ukmergė",
      "karjera"
    ],
    "description": "Auklė pozicija Ukmergė. Auklė / babysitter — nuolatinė. Oficialus įdarbinimas, socialinės garantijos.",
    "sellerId": "seller-job-2",
    "createdAt": "2026-06-17T10:39:00.000Z",
    "attributes": {
      "position": "Auklė",
      "schedule": "Pilnas etatas",
      "experience": "2+ m."
    }
  },
  {
    "id": "lt-clo-001",
    "title": "Nike Air Max 270 batai 43 d.",
    "price": 85,
    "location": "Kaunas",
    "distanceKm": 31,
    "contact": "Tel. +370 66000000",
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "nike",
      "batai",
      "sportas",
      "kaunas",
      "drabužiai"
    ],
    "description": "Parduodu Nike Air Max 270 batai 43 d.. Dydis 43, būklė: Gera. Kaunas, galiu siųsti LP Express.",
    "sellerId": "seller-clo-1",
    "createdAt": "2026-06-09T14:00:00.000Z",
    "attributes": {
      "brand": "Nike",
      "size": "43",
      "condition": "Gera"
    }
  },
  {
    "id": "lt-clo-002",
    "title": "Zara vilnonė striukė M",
    "price": 45,
    "location": "Alytus",
    "distanceKm": 32.3,
    "contact": "Tel. +370 66007919",
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "zara",
      "striukė",
      "drabužiai",
      "alytus",
      "drabužiai"
    ],
    "description": "Zara vilnonė striukė M — Zara prekė. Dydis M. Naudota kelis kartus, be defektų. Alytus.",
    "sellerId": "seller-clo-2",
    "createdAt": "2026-06-10T14:06:00.000Z",
    "attributes": {
      "brand": "Zara",
      "size": "M",
      "condition": "Kaip nauja"
    }
  },
  {
    "id": "lt-clo-003",
    "title": "Mango suknelė vakariniam renginiui",
    "price": 38,
    "location": "Utena",
    "distanceKm": 33.6,
    "contact": "Tel. +370 66015838",
    "image": "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "mango",
      "suknelė",
      "drabužiai",
      "utena",
      "drabužiai"
    ],
    "description": "Tvarkingas mango suknelė vakariniam renginiui, dydis S. Originalus, ne fake. Perduodu Utena centre.",
    "sellerId": "seller-clo-3",
    "createdAt": "2026-06-11T14:12:00.000Z",
    "attributes": {
      "brand": "Mango",
      "size": "S",
      "condition": "Nauja"
    }
  },
  {
    "id": "lt-clo-004",
    "title": "Levi's 501 džinsai W32 L32",
    "price": 42,
    "location": "Ukmergė",
    "distanceKm": 34.9,
    "contact": "Tel. +370 66023757",
    "image": "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "levis",
      "džinsai",
      "drabužiai",
      "ukmergė",
      "drabužiai"
    ],
    "description": "Levi's 501 džinsai W32 L32. Būklė: Gera. Dydis W32 L32. Ukmergė, galimas siuntimas.",
    "sellerId": "seller-clo-4",
    "createdAt": "2026-06-12T14:18:00.000Z",
    "attributes": {
      "brand": "Levi's",
      "size": "W32 L32",
      "condition": "Gera"
    },
    "visibilityTier": "plus"
  },
  {
    "id": "lt-clo-005",
    "title": "North Face žieminė striukė L",
    "price": 120,
    "location": "Druskininkai",
    "distanceKm": 36.2,
    "contact": "Tel. +370 66031676",
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "north face",
      "striukė",
      "žiemą",
      "druskininkai",
      "drabužiai"
    ],
    "description": "Parduodu North Face žieminė striukė L. Dydis L, būklė: Labai gera. Druskininkai, galiu siųsti LP Express.",
    "sellerId": "seller-clo-5",
    "createdAt": "2026-06-13T14:24:00.000Z",
    "attributes": {
      "brand": "The North Face",
      "size": "L",
      "condition": "Labai gera"
    }
  },
  {
    "id": "lt-clo-006",
    "title": "Adidas Ultraboost batai 42 d.",
    "price": 95,
    "location": "Kretinga",
    "distanceKm": 37.5,
    "contact": "Tel. +370 66039595",
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "adidas",
      "batai",
      "bėgimas",
      "kretinga",
      "drabužiai"
    ],
    "description": "Adidas Ultraboost batai 42 d. — Adidas prekė. Dydis 42. Naudota kelis kartus, be defektų. Kretinga.",
    "sellerId": "seller-clo-1",
    "createdAt": "2026-06-14T14:30:00.000Z",
    "attributes": {
      "brand": "Adidas",
      "size": "42",
      "condition": "Gera"
    }
  },
  {
    "id": "lt-clo-007",
    "title": "Michael Kors rankinė",
    "price": 75,
    "location": "Radviliškis",
    "distanceKm": 38.8,
    "contact": "Tel. +370 66047514",
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "rankinė",
      "moteriška",
      "aksesuaras",
      "radviliškis",
      "drabužiai"
    ],
    "description": "Tvarkingas michael kors rankinė, dydis —. Originalus, ne fake. Perduodu Radviliškis centre.",
    "sellerId": "seller-clo-2",
    "createdAt": "2026-06-15T14:36:00.000Z",
    "attributes": {
      "brand": "Michael Kors",
      "size": "—",
      "condition": "Kaip nauja"
    }
  },
  {
    "id": "lt-clo-008",
    "title": "H&M vaikiška striukė 128 cm",
    "price": 18,
    "location": "Klaipėda",
    "distanceKm": 40.1,
    "contact": "Tel. +370 66055433",
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "vaikai",
      "striukė",
      "drabužiai",
      "klaipėda",
      "drabužiai"
    ],
    "description": "H&M vaikiška striukė 128 cm. Būklė: Gera. Dydis 128. Klaipėda, galimas siuntimas.",
    "sellerId": "seller-clo-3",
    "createdAt": "2026-06-16T14:42:00.000Z",
    "attributes": {
      "brand": "H&M",
      "size": "128",
      "condition": "Gera"
    }
  },
  {
    "id": "lt-clo-009",
    "title": "Tommy Hilfiger polo marškinėliai",
    "price": 28,
    "location": "Marijampolė",
    "distanceKm": 41.4,
    "contact": "Tel. +370 66063352",
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "tommy",
      "marškinėliai",
      "drabužiai",
      "marijampolė",
      "drabužiai"
    ],
    "description": "Parduodu Tommy Hilfiger polo marškinėliai. Dydis L, būklė: Nauja. Marijampolė, galiu siųsti LP Express.",
    "sellerId": "seller-clo-4",
    "createdAt": "2026-06-17T14:48:00.000Z",
    "attributes": {
      "brand": "Tommy Hilfiger",
      "size": "L",
      "condition": "Nauja"
    }
  },
  {
    "id": "lt-clo-010",
    "title": "Puma sportiniai kostiumai",
    "price": 55,
    "location": "Kupiškis",
    "distanceKm": 42.7,
    "contact": "Tel. +370 66071271",
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "puma",
      "sportas",
      "drabužiai",
      "kupiškis",
      "drabužiai"
    ],
    "description": "Puma sportiniai kostiumai — Puma prekė. Dydis M. Naudota kelis kartus, be defektų. Kupiškis.",
    "sellerId": "seller-clo-5",
    "createdAt": "2026-06-18T14:54:00.000Z",
    "attributes": {
      "brand": "Puma",
      "size": "M",
      "condition": "Gera"
    }
  },
  {
    "id": "lt-clo-011",
    "title": "Timberland aulinukai 44 d.",
    "price": 110,
    "location": "Palanga",
    "distanceKm": 1,
    "contact": "Tel. +370 66079190",
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "timberland",
      "batai",
      "žiemą",
      "palanga",
      "drabužiai"
    ],
    "description": "Tvarkingas timberland aulinukai 44 d., dydis 44. Originalus, ne fake. Perduodu Palanga centre.",
    "sellerId": "seller-clo-1",
    "createdAt": "2026-06-19T15:00:00.000Z",
    "attributes": {
      "brand": "Timberland",
      "size": "44",
      "condition": "Labai gera"
    }
  },
  {
    "id": "lt-clo-012",
    "title": "Reserved palto modelis moterims",
    "price": 68,
    "location": "Rokiškis",
    "distanceKm": 2.3,
    "contact": "Tel. +370 66087109",
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "reserved",
      "paltas",
      "drabužiai",
      "rokiškis",
      "drabužiai"
    ],
    "description": "Reserved palto modelis moterims. Būklė: Gera. Dydis M. Rokiškis, galimas siuntimas.",
    "sellerId": "seller-clo-2",
    "createdAt": "2026-06-20T15:06:00.000Z",
    "attributes": {
      "brand": "Reserved",
      "size": "M",
      "condition": "Gera"
    }
  },
  {
    "id": "lt-el-001",
    "title": "iPhone 15 Pro 256 GB",
    "price": 980,
    "location": "Klaipėda",
    "distanceKm": 1,
    "contact": "Tel. +370 62000000",
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "iphone",
      "telefonas",
      "apple",
      "klaipėda",
      "elektronika"
    ],
    "description": "Parduodu iPhone 15 Pro 256 GB — naudotas, bet be defektų. Ekranas be įbrėžimų, baterija laiko puikiai. Komplektas su dėklu ir įkrovikliu. Galima apžiūrėti Klaipėda.",
    "sellerId": "seller-el-1",
    "createdAt": "2026-06-11T10:00:00.000Z",
    "visibilityTier": "top",
    "promoted": true
  },
  {
    "id": "lt-el-002",
    "title": "iPhone 14 128 GB",
    "price": 650,
    "location": "Mažeikiai",
    "distanceKm": 2.3,
    "contact": "Tel. +370 62007919",
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "iphone",
      "telefonas",
      "mažeikiai",
      "elektronika"
    ],
    "description": "iPhone 14 128 GB — pirktas oficialioje parduotuvėje, liko garantija. Visi priedai, dėžutė ir kvitas. Perduodu Mažeikiai centre.",
    "sellerId": "seller-el-2",
    "createdAt": "2026-06-12T10:07:00.000Z"
  },
  {
    "id": "lt-el-003",
    "title": "Samsung Galaxy S24 Ultra",
    "price": 950,
    "location": "Tauragė",
    "distanceKm": 3.6,
    "contact": "Tel. +370 62015838",
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "samsung",
      "telefonas",
      "android",
      "tauragė",
      "elektronika"
    ],
    "description": "Tvarkingas Samsung Galaxy S24 Ultra, naudotas namuose. Be vandens pažeidimų, visos funkcijos veikia. Greitas susitikimas Tauragė.",
    "sellerId": "seller-el-3",
    "createdAt": "2026-06-13T10:14:00.000Z"
  },
  {
    "id": "lt-el-004",
    "title": "MacBook Air M2 13\"",
    "price": 1050,
    "location": "Druskininkai",
    "distanceKm": 4.9,
    "contact": "Tel. +370 62023757",
    "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "macbook",
      "apple",
      "kompiuteris",
      "druskininkai",
      "elektronika"
    ],
    "description": "MacBook Air M2 13\" — atnaujintas programinė įranga, Face ID/Touch ID veikia. Idealus kasdieniam naudojimui. Druskininkai, galiu atvežti.",
    "sellerId": "seller-el-4",
    "createdAt": "2026-06-14T10:21:00.000Z",
    "visibilityTier": "plus"
  },
  {
    "id": "lt-el-005",
    "title": "iPad Pro 11\" M2",
    "price": 810,
    "location": "Visaginas",
    "distanceKm": 6.2,
    "contact": "Tel. +370 62031676",
    "image": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "ipad",
      "planšetė",
      "visaginas",
      "elektronika"
    ],
    "description": "Parduodu iPad Pro 11\" M2 — naudotas, bet be defektų. Ekranas be įbrėžimų, baterija laiko puikiai. Komplektas su dėklu ir įkrovikliu. Galima apžiūrėti Visaginas.",
    "sellerId": "seller-el-5",
    "createdAt": "2026-06-15T10:28:00.000Z"
  },
  {
    "id": "lt-el-006",
    "title": "PlayStation 5 + 2 pultai",
    "price": 480,
    "location": "Vilnius",
    "distanceKm": 7.5,
    "contact": "Tel. +370 62039595",
    "image": "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "ps5",
      "žaidimai",
      "konsolė",
      "vilnius",
      "elektronika"
    ],
    "description": "PlayStation 5 + 2 pultai — pirktas oficialioje parduotuvėje, liko garantija. Visi priedai, dėžutė ir kvitas. Perduodu Vilnius centre.",
    "sellerId": "seller-el-1",
    "createdAt": "2026-06-16T10:35:00.000Z"
  },
  {
    "id": "lt-el-007",
    "title": "Dyson V15 Detect",
    "price": 480,
    "location": "Alytus",
    "distanceKm": 8.8,
    "contact": "Tel. +370 62047514",
    "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "dyson",
      "siurblys",
      "namams",
      "alytus",
      "elektronika"
    ],
    "description": "Tvarkingas Dyson V15 Detect, naudotas namuose. Be vandens pažeidimų, visos funkcijos veikia. Greitas susitikimas Alytus.",
    "sellerId": "seller-el-2",
    "createdAt": "2026-06-17T10:42:00.000Z"
  },
  {
    "id": "lt-el-008",
    "title": "Sony WH-1000XM5 ausinės",
    "price": 290,
    "location": "Kupiškis",
    "distanceKm": 10.1,
    "contact": "Tel. +370 62055433",
    "image": "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "sony",
      "ausinės",
      "bluetooth",
      "kupiškis",
      "elektronika"
    ],
    "description": "Sony WH-1000XM5 ausinės — atnaujintas programinė įranga, Face ID/Touch ID veikia. Idealus kasdieniam naudojimui. Kupiškis, galiu atvežti.",
    "sellerId": "seller-el-3",
    "createdAt": "2026-06-18T10:49:00.000Z"
  },
  {
    "id": "lt-el-009",
    "title": "iPhone 15 Pro 256 GB",
    "price": 1040,
    "location": "Jonava",
    "distanceKm": 11.4,
    "contact": "Tel. +370 62063352",
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "iphone",
      "telefonas",
      "apple",
      "jonava",
      "elektronika"
    ],
    "description": "Parduodu iPhone 15 Pro 256 GB — naudotas, bet be defektų. Ekranas be įbrėžimų, baterija laiko puikiai. Komplektas su dėklu ir įkrovikliu. Galima apžiūrėti Jonava.",
    "sellerId": "seller-el-4",
    "createdAt": "2026-06-19T10:56:00.000Z"
  },
  {
    "id": "lt-el-010",
    "title": "iPhone 14 128 GB",
    "price": 620,
    "location": "Plungė",
    "distanceKm": 12.7,
    "contact": "Tel. +370 62071271",
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "iphone",
      "telefonas",
      "plungė",
      "elektronika"
    ],
    "description": "iPhone 14 128 GB — pirktas oficialioje parduotuvėje, liko garantija. Visi priedai, dėžutė ir kvitas. Perduodu Plungė centre.",
    "sellerId": "seller-el-5",
    "createdAt": "2026-06-20T11:03:00.000Z"
  },
  {
    "id": "lt-el-011",
    "title": "Samsung Galaxy S24 Ultra",
    "price": 920,
    "location": "Radviliškis",
    "distanceKm": 11,
    "contact": "Tel. +370 62079190",
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "samsung",
      "telefonas",
      "android",
      "radviliškis",
      "elektronika"
    ],
    "description": "Tvarkingas Samsung Galaxy S24 Ultra, naudotas namuose. Be vandens pažeidimų, visos funkcijos veikia. Greitas susitikimas Radviliškis.",
    "sellerId": "seller-el-1",
    "createdAt": "2026-06-21T11:10:00.000Z"
  },
  {
    "id": "lt-el-012",
    "title": "MacBook Air M2 13\"",
    "price": 1110,
    "location": "Šiauliai",
    "distanceKm": 12.3,
    "contact": "Tel. +370 62087109",
    "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "macbook",
      "apple",
      "kompiuteris",
      "šiauliai",
      "elektronika"
    ],
    "description": "MacBook Air M2 13\" — atnaujintas programinė įranga, Face ID/Touch ID veikia. Idealus kasdieniam naudojimui. Šiauliai, galiu atvežti.",
    "sellerId": "seller-el-2",
    "createdAt": "2026-06-22T11:17:00.000Z"
  },
  {
    "id": "lt-home-001",
    "title": "Sofa-lova su daiktų saugykla",
    "price": 420,
    "location": "Utena",
    "distanceKm": 11,
    "contact": "Tel. +370 67000000",
    "image": "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "sofa",
      "baldai",
      "svetainė",
      "utena",
      "baldai"
    ],
    "description": "Parduodu sofa-lova su daiktų saugykla — Utena. Tvarkinga būklė, be įbrėžimų. Galimas pristatymas mieste.",
    "sellerId": "seller-home-1",
    "createdAt": "2026-06-13T13:00:00.000Z"
  },
  {
    "id": "lt-home-002",
    "title": "Stiklo valgomojo stalas su 6 kėdėmis",
    "price": 380,
    "location": "Tauragė",
    "distanceKm": 12.3,
    "contact": "Tel. +370 67007919",
    "image": "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "stalas",
      "baldai",
      "virtuvė",
      "tauragė",
      "baldai"
    ],
    "description": "Stiklo valgomojo stalas su 6 kėdėmis iš Tauragė. Naudotas namuose, rūpestingai prižiūrėtas. Galite apžiūrėti gyvai.",
    "sellerId": "seller-home-2",
    "createdAt": "2026-06-14T13:08:00.000Z"
  },
  {
    "id": "lt-home-003",
    "title": "Virtuvės komplektas — matinė balta",
    "price": 1850,
    "location": "Jonava",
    "distanceKm": 13.6,
    "contact": "Tel. +370 67015838",
    "image": "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "virtuvė",
      "baldai",
      "komplektas",
      "jonava",
      "baldai"
    ],
    "description": "Virtuvės komplektas — matinė balta — kokybiškas, funkcionalus. Jonava. Greitas atsiėmimas arba pristatymas.",
    "sellerId": "seller-home-3",
    "createdAt": "2026-06-15T13:16:00.000Z"
  },
  {
    "id": "lt-home-004",
    "title": "King size lova su čiužiniu",
    "price": 650,
    "location": "Rokiškis",
    "distanceKm": 14.9,
    "contact": "Tel. +370 67023757",
    "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "lova",
      "miegamasis",
      "baldai",
      "rokiškis",
      "baldai"
    ],
    "description": "Baldų pasiūlymas: King size lova su čiužiniu. Vieta: Rokiškis. Be rūdžių, defektų ar stipresnio nusidėvėjimo.",
    "sellerId": "seller-home-4",
    "createdAt": "2026-06-16T13:24:00.000Z"
  },
  {
    "id": "lt-home-005",
    "title": "Spinta-sliding 3 durų",
    "price": 520,
    "location": "Kretinga",
    "distanceKm": 16.2,
    "contact": "Tel. +370 67031676",
    "image": "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "spinta",
      "baldai",
      "miegamasis",
      "kretinga",
      "baldai"
    ],
    "description": "Parduodu spinta-sliding 3 durų — Kretinga. Tvarkinga būklė, be įbrėžimų. Galimas pristatymas mieste.",
    "sellerId": "seller-home-1",
    "createdAt": "2026-06-17T13:32:00.000Z",
    "visibilityTier": "plus"
  },
  {
    "id": "lt-home-006",
    "title": "Ergonominė darbo kėdė",
    "price": 145,
    "location": "Gargždai",
    "distanceKm": 17.5,
    "contact": "Tel. +370 67039595",
    "image": "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "kėdė",
      "biuras",
      "baldai",
      "gargždai",
      "baldai"
    ],
    "description": "Ergonominė darbo kėdė iš Gargždai. Naudotas namuose, rūpestingai prižiūrėtas. Galite apžiūrėti gyvai.",
    "sellerId": "seller-home-2",
    "createdAt": "2026-06-18T13:40:00.000Z"
  },
  {
    "id": "lt-home-007",
    "title": "TV komoda su LED apšvietimu",
    "price": 210,
    "location": "Vilnius",
    "distanceKm": 18.8,
    "contact": "Tel. +370 67047514",
    "image": "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "komoda",
      "baldai",
      "svetainė",
      "vilnius",
      "baldai"
    ],
    "description": "TV komoda su LED apšvietimu — kokybiškas, funkcionalus. Vilnius. Greitas atsiėmimas arba pristatymas.",
    "sellerId": "seller-home-3",
    "createdAt": "2026-06-19T13:48:00.000Z"
  },
  {
    "id": "lt-home-008",
    "title": "Knygų lentyna 5 skyrių",
    "price": 95,
    "location": "Šiauliai",
    "distanceKm": 20.1,
    "contact": "Tel. +370 67055433",
    "image": "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "lentyna",
      "baldai",
      "namai",
      "šiauliai",
      "baldai"
    ],
    "description": "Baldų pasiūlymas: Knygų lentyna 5 skyrių. Vieta: Šiauliai. Be rūdžių, defektų ar stipresnio nusidėvėjimo.",
    "sellerId": "seller-home-4",
    "createdAt": "2026-06-20T13:56:00.000Z"
  },
  {
    "id": "lt-home-009",
    "title": "Baro kėdės 2 vnt. metalinės",
    "price": 120,
    "location": "Marijampolė",
    "distanceKm": 21.4,
    "contact": "Tel. +370 67063352",
    "image": "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "kėdės",
      "baldai",
      "virtuvė",
      "marijampolė",
      "baldai"
    ],
    "description": "Parduodu baro kėdės 2 vnt. metalinės — Marijampolė. Tvarkinga būklė, be įbrėžimų. Galimas pristatymas mieste.",
    "sellerId": "seller-home-1",
    "createdAt": "2026-06-21T14:04:00.000Z"
  },
  {
    "id": "lt-home-010",
    "title": "Vaiko kambario komplektas",
    "price": 480,
    "location": "Utena",
    "distanceKm": 22.7,
    "contact": "Tel. +370 67071271",
    "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "vaikams",
      "baldai",
      "kambarys",
      "utena",
      "baldai"
    ],
    "description": "Vaiko kambario komplektas iš Utena. Naudotas namuose, rūpestingai prižiūrėtas. Galite apžiūrėti gyvai.",
    "sellerId": "seller-home-2",
    "createdAt": "2026-06-22T14:12:00.000Z"
  },
  {
    "id": "lt-home-011",
    "title": "Šviestuvas + staliukas komplektas",
    "price": 165,
    "location": "Tauragė",
    "distanceKm": 21,
    "contact": "Tel. +370 67079190",
    "image": "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "šviestuvas",
      "baldai",
      "svetainė",
      "tauragė",
      "baldai"
    ],
    "description": "Šviestuvas + staliukas komplektas — kokybiškas, funkcionalus. Tauragė. Greitas atsiėmimas arba pristatymas.",
    "sellerId": "seller-home-3",
    "createdAt": "2026-06-23T14:20:00.000Z"
  },
  {
    "id": "lt-svc-001",
    "title": "Automobilio detailing — pilnas paketas",
    "price": 120,
    "priceLabel": "nuo 120€",
    "location": "Šiauliai",
    "distanceKm": 21,
    "contact": "Tel. +370 63000000",
    "image": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "detailing",
      "plovimas",
      "automobilis",
      "šiauliai",
      "paslauga"
    ],
    "description": "Automobilio detailing — pilnas paketas — dirbame Šiauliai ir apylinkėse. Profesionali įranga, sąskaitos faktūros. Skambinkite dėl laiko.",
    "sellerId": "seller-svc-1",
    "createdAt": "2026-06-16T09:00:00.000Z",
    "providerVerified": true,
    "visibilityTier": "top"
  },
  {
    "id": "lt-svc-002",
    "title": "Padangų montavimas ir balansavimas",
    "price": 35,
    "priceLabel": "nuo 35€",
    "location": "Mažeikiai",
    "distanceKm": 22.3,
    "contact": "Tel. +370 63007919",
    "image": "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "padangos",
      "montavimas",
      "autoservisas",
      "mažeikiai",
      "paslauga"
    ],
    "description": "Siūlome padangų montavimas ir balansavimas Mažeikiai regione. Greitas aptarnavimas, patyrę meistrai, garantija darbams.",
    "sellerId": "seller-svc-2",
    "createdAt": "2026-06-17T09:11:00.000Z",
    "providerVerified": true
  },
  {
    "id": "lt-svc-003",
    "title": "Paruošimas techninei apžiūrai",
    "price": 45,
    "priceLabel": "nuo 45€",
    "location": "Telšiai",
    "distanceKm": 23.6,
    "contact": "Tel. +370 63015838",
    "image": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "ta",
      "techninė",
      "autoservisas",
      "telšiai",
      "paslauga"
    ],
    "description": "Paruošimas techninei apžiūrai. Atvykstame į vietą Telšiai mieste. Skaidri kainodara, be paslėptų mokesčių.",
    "sellerId": "seller-svc-3",
    "createdAt": "2026-06-18T09:22:00.000Z",
    "providerVerified": true
  },
  {
    "id": "lt-svc-004",
    "title": "Santechnikas — avarinis iškvietimas",
    "price": 50,
    "priceLabel": "nuo 50€",
    "location": "Jonava",
    "distanceKm": 24.9,
    "contact": "Tel. +370 63023757",
    "image": "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "santechnikas",
      "remontas",
      "paslauga",
      "jonava",
      "paslauga"
    ],
    "description": "Santechnikas — avarinis iškvietimas — ilgametė patirtis, rekomendacijos klientų. Jonava ir visa Lietuva.",
    "sellerId": "seller-svc-4",
    "createdAt": "2026-06-19T09:33:00.000Z",
    "providerVerified": true
  },
  {
    "id": "lt-svc-005",
    "title": "Elektrikas — rozetės, apšvietimas",
    "price": 40,
    "priceLabel": "nuo 40€",
    "location": "Pasvalys",
    "distanceKm": 26.2,
    "contact": "Tel. +370 63031676",
    "image": "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "elektrikas",
      "montavimas",
      "pasvalys",
      "paslauga"
    ],
    "description": "Elektrikas — rozetės, apšvietimas — dirbame Pasvalys ir apylinkėse. Profesionali įranga, sąskaitos faktūros. Skambinkite dėl laiko.",
    "sellerId": "seller-svc-1",
    "createdAt": "2026-06-20T09:44:00.000Z",
    "providerVerified": true
  },
  {
    "id": "lt-svc-006",
    "title": "Buto valymas po remonto",
    "price": 80,
    "priceLabel": "nuo 80€",
    "location": "Šilutė",
    "distanceKm": 27.5,
    "contact": "Tel. +370 63039595",
    "image": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "valymas",
      "butas",
      "paslauga",
      "šilutė",
      "paslauga"
    ],
    "description": "Siūlome buto valymas po remonto Šilutė regione. Greitas aptarnavimas, patyrę meistrai, garantija darbams.",
    "sellerId": "seller-svc-2",
    "createdAt": "2026-06-21T09:55:00.000Z",
    "providerVerified": true
  },
  {
    "id": "lt-svc-007",
    "title": "Evacuatorius 24/7 visoje Lietuvoje",
    "price": 40,
    "priceLabel": "nuo 40€",
    "location": "Vilnius",
    "distanceKm": 28.8,
    "contact": "Tel. +370 63047514",
    "image": "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "evakuatorius",
      "pagalba",
      "kelyje",
      "vilnius",
      "paslauga"
    ],
    "description": "Evacuatorius 24/7 visoje Lietuvoje. Atvykstame į vietą Vilnius mieste. Skaidri kainodara, be paslėptų mokesčių.",
    "sellerId": "seller-svc-3",
    "createdAt": "2026-06-22T10:06:00.000Z",
    "providerVerified": true
  },
  {
    "id": "lt-svc-008",
    "title": "Kėbulų dažymas — profesionaliai",
    "price": 350,
    "priceLabel": "nuo 350€",
    "location": "Panevėžys",
    "distanceKm": 30.1,
    "contact": "Tel. +370 63055433",
    "image": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "dažymas",
      "kėbulas",
      "autoservisas",
      "panevėžys",
      "paslauga"
    ],
    "description": "Kėbulų dažymas — profesionaliai — ilgametė patirtis, rekomendacijos klientų. Panevėžys ir visa Lietuva.",
    "sellerId": "seller-svc-4",
    "createdAt": "2026-06-23T10:17:00.000Z",
    "providerVerified": true
  },
  {
    "id": "lt-svc-009",
    "title": "Variklio diagnostika OBD",
    "price": 25,
    "priceLabel": "25€",
    "location": "Biržai",
    "distanceKm": 31.4,
    "contact": "Tel. +370 63063352",
    "image": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "diagnostika",
      "obd",
      "autoservisas",
      "biržai",
      "paslauga"
    ],
    "description": "Variklio diagnostika OBD — dirbame Biržai ir apylinkėse. Profesionali įranga, sąskaitos faktūros. Skambinkite dėl laiko.",
    "sellerId": "seller-svc-1",
    "createdAt": "2026-06-24T10:28:00.000Z",
    "providerVerified": true
  },
  {
    "id": "lt-svc-010",
    "title": "Vėdinimo ir kondicionavimo aptarnavimas",
    "price": 60,
    "priceLabel": "nuo 60€",
    "location": "Tauragė",
    "distanceKm": 32.7,
    "contact": "Tel. +370 63071271",
    "image": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "kondicionierius",
      "klimate",
      "paslauga",
      "tauragė",
      "paslauga"
    ],
    "description": "Siūlome vėdinimo ir kondicionavimo aptarnavimas Tauragė regione. Greitas aptarnavimas, patyrę meistrai, garantija darbams.",
    "sellerId": "seller-svc-2",
    "createdAt": "2026-06-25T10:39:00.000Z",
    "providerVerified": true
  },
  {
    "id": "lt-oth-001",
    "title": "Kalnų dviratis 29\" ratais",
    "price": 380,
    "location": "Telšiai",
    "distanceKm": 31,
    "contact": "Tel. +370 68000000",
    "image": "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&h=600&fit=crop&auto=format",
    "category": "other",
    "tags": [
      "dviratis",
      "sportas",
      "laukas",
      "telšiai",
      "kita"
    ],
    "description": "Parduodu kalnų dviratis 29\" ratais — Telšiai. Tvarkinga, veikianti, paruošta naudojimui.",
    "sellerId": "seller-oth-1",
    "createdAt": "2026-06-19T16:00:00.000Z"
  },
  {
    "id": "lt-oth-002",
    "title": "Vaikiškas vežimėlis 3in1",
    "price": 220,
    "location": "Druskininkai",
    "distanceKm": 32.3,
    "contact": "Tel. +370 68007919",
    "image": "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop&auto=format",
    "category": "other",
    "tags": [
      "vežimėlis",
      "vaikai",
      "kūdikis",
      "druskininkai",
      "kita"
    ],
    "description": "Vaikiškas vežimėlis 3in1 iš Druskininkai. Gera būklė, sąžiningas pardavėjas. Galima apžiūrėti.",
    "sellerId": "seller-oth-2",
    "createdAt": "2026-06-20T16:12:00.000Z"
  },
  {
    "id": "lt-oth-003",
    "title": "Bosch elektrinių įrankių komplektas",
    "price": 195,
    "location": "Šilutė",
    "distanceKm": 33.6,
    "contact": "Tel. +370 68015838",
    "image": "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&h=600&fit=crop&auto=format",
    "category": "other",
    "tags": [
      "įrankiai",
      "bosch",
      "remontas",
      "šilutė",
      "kita"
    ],
    "description": "Bosch elektrinių įrankių komplektas — Šilutė. Visi komplektai vietoje, be paslėptų defektų.",
    "sellerId": "seller-oth-3",
    "createdAt": "2026-06-21T16:24:00.000Z"
  },
  {
    "id": "lt-oth-004",
    "title": "Universitetų vadovėlių rinkinys",
    "price": 45,
    "location": "Klaipėda",
    "distanceKm": 34.9,
    "contact": "Tel. +370 68023757",
    "image": "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&h=600&fit=crop&auto=format",
    "category": "other",
    "tags": [
      "knygos",
      "studijos",
      "vadovėliai",
      "klaipėda",
      "kita"
    ],
    "description": "Pasiūlymas Klaipėda: Universitetų vadovėlių rinkinys. Skambinkite dėl detalių ir apžiūros laiko.",
    "sellerId": "seller-oth-1",
    "createdAt": "2026-06-22T16:36:00.000Z"
  },
  {
    "id": "lt-oth-005",
    "title": "Sodo žoliapjovė + trimeris",
    "price": 160,
    "location": "Biržai",
    "distanceKm": 36.2,
    "contact": "Tel. +370 68031676",
    "image": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&h=600&fit=crop&auto=format",
    "category": "other",
    "tags": [
      "sodas",
      "technika",
      "žolė",
      "biržai",
      "kita"
    ],
    "description": "Parduodu sodo žoliapjovė + trimeris — Biržai. Tvarkinga, veikianti, paruošta naudojimui.",
    "sellerId": "seller-oth-2",
    "createdAt": "2026-06-23T16:48:00.000Z"
  },
  {
    "id": "lt-ai-001",
    "title": "AI atranda: BMW 320d — karšta prekė Kaune",
    "price": 8900,
    "location": "Kaunas",
    "distanceKm": 1,
    "contact": "Tel. +370 69000000",
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    "category": "vehicles",
    "tags": [
      "ai-atranda",
      "automobilis",
      "bmw",
      "kaunas"
    ],
    "description": "VAUTO AI atrado populiariausią automobilio pasiūlymą Kauno regione. BMW 320d, tvarkinga serviso istorija, didelis peržiūrų skaičius per 24 val.",
    "sellerId": "seller-ai-1",
    "createdAt": "2026-06-21T12:00:00.000Z"
  },
  {
    "id": "lt-ai-002",
    "title": "AI atranda: 2 k. butas Naujamiestyje",
    "price": 178000,
    "location": "Vilnius",
    "distanceKm": 2.3,
    "contact": "Tel. +370 69007919",
    "image": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&auto=format",
    "category": "real_estate",
    "tags": [
      "ai-atranda",
      "butas",
      "vilnius",
      "nekilnojamasis"
    ],
    "description": "AI atrinko geriausią kainos ir vietos santykį Vilniuje: 2 kambarių butas Naujamiestyje, renovuotas, arti viešojo transporto.",
    "sellerId": "seller-ai-2",
    "createdAt": "2026-06-22T12:09:00.000Z",
    "visibilityTier": "plus"
  },
  {
    "id": "lt-ai-003",
    "title": "AI atranda: iPhone 15 Pro 256 GB",
    "price": 920,
    "location": "Klaipėda",
    "distanceKm": 3.6,
    "contact": "Tel. +370 69015838",
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&h=600&fit=crop&auto=format",
    "category": "electronics",
    "tags": [
      "ai-atranda",
      "iphone",
      "telefonas",
      "klaipėda"
    ],
    "description": "Populiariausias elektronikos skelbimas Klaipėdoje — iPhone 15 Pro, pilna komplektacija, baterijos sveikata 94%.",
    "sellerId": "seller-ai-3",
    "createdAt": "2026-06-23T12:18:00.000Z"
  },
  {
    "id": "lt-ai-004",
    "title": "AI atranda: auto detailing premium",
    "price": 120,
    "priceLabel": "Nuo 120€",
    "location": "Šiauliai",
    "distanceKm": 4.9,
    "contact": "Tel. +370 69023757",
    "image": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop&auto=format",
    "category": "services",
    "tags": [
      "ai-atranda",
      "detailing",
      "automobilis",
      "šiauliai"
    ],
    "description": "AI rekomenduoja geriausiai vertinamą auto detailing paslaugą Šiauliuose — keraminių dangų aplikavimas, poliravimas, salono valymas.",
    "sellerId": "seller-ai-4",
    "createdAt": "2026-06-24T12:27:00.000Z"
  },
  {
    "id": "lt-ai-005",
    "title": "AI atranda: North Face striukė vyrams",
    "price": 145,
    "location": "Panevėžys",
    "distanceKm": 6.2,
    "contact": "Tel. +370 69031676",
    "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop&auto=format",
    "category": "clothing",
    "tags": [
      "ai-atranda",
      "striukė",
      "drabužiai",
      "panevėžys"
    ],
    "description": "Dažniausiai saugomas drabužių skelbimas Panevėžio regione — The North Face striukė, dydis L, be defektų.",
    "sellerId": "seller-ai-1",
    "createdAt": "2026-06-25T12:36:00.000Z"
  },
  {
    "id": "lt-ai-006",
    "title": "AI atranda: skandinaviška sofa-lova",
    "price": 420,
    "location": "Marijampolė",
    "distanceKm": 7.5,
    "contact": "Tel. +370 69039595",
    "image": "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=600&fit=crop&auto=format",
    "category": "home",
    "tags": [
      "ai-atranda",
      "baldai",
      "sofa",
      "marijampolė"
    ],
    "description": "AI atrado geriausią baldų pasiūlymą Marijampolėje — skandinaviško stiliaus sofa-lova, be dėmių, pristatymas galimas.",
    "sellerId": "seller-ai-2",
    "createdAt": "2026-06-26T12:45:00.000Z"
  },
  {
    "id": "lt-ai-007",
    "title": "AI atranda: sandėlio darbuotojas",
    "price": 1450,
    "priceLabel": "Nuo 1450€/mėn.",
    "location": "Alytus",
    "distanceKm": 8.8,
    "contact": "Tel. +370 69047514",
    "image": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=600&fit=crop&auto=format",
    "category": "jobs",
    "tags": [
      "ai-atranda",
      "darbas",
      "sandėlis",
      "alytus"
    ],
    "description": "Populiariausias darbo skelbimas Alytaus regione — sandėlio darbuotojas, pilnas etatas, oficialus darbo santykis, apmokamas mokymas.",
    "sellerId": "seller-ai-3",
    "createdAt": "2026-06-27T12:54:00.000Z"
  },
  {
    "id": "lt-ai-008",
    "title": "AI atranda: kalnų dviratis 29\"",
    "price": 520,
    "location": "Mažeikiai",
    "distanceKm": 10.1,
    "contact": "Tel. +370 69055433",
    "image": "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&h=600&fit=crop&auto=format",
    "category": "other",
    "tags": [
      "ai-atranda",
      "dviratis",
      "sportas",
      "mažeikiai"
    ],
    "description": "AI atrinko geriausią laisvalaikio prekę Mažeikiuose — kalnų dviratis 29\" ratais, hidrauliniai stabdžiai, nedaug naudotas.",
    "sellerId": "seller-ai-4",
    "createdAt": "2026-06-28T13:03:00.000Z"
  }
] as LegacyListingInput[];
