/**
 * Trusted fixture catalog simulating VAUTO DB rows for offline NL Search tests.
 * These are NOT LLM-generated at runtime — static fixtures only.
 */

import type { SearchListingRecord } from "../search-schema.js";

export const NL_SEARCH_FIXTURE_CATALOG: SearchListingRecord[] = [
  {
    id: "l-bmw-e46-1",
    title: "BMW e46 2003 dyzelis",
    price: 2200,
    location: "Vilnius",
    category: "vehicles",
    brand: "BMW",
    model: "e46",
    year: 2003,
    mileage: 280000,
    fuel: "diesel",
    transmission: "manual",
    distanceKm: 8,
    createdAt: "2026-08-01T10:00:00.000Z",
    sellerVerified: true,
    status: "active",
    visibility: "public",
  },
  {
    id: "l-audi-a4-1",
    title: "Audi A4 quattro automatas",
    price: 8900,
    location: "Kaunas",
    category: "vehicles",
    brand: "Audi",
    model: "A4",
    year: 2015,
    mileage: 160000,
    fuel: "petrol",
    transmission: "automatic",
    distanceKm: 12,
    createdAt: "2026-08-02T10:00:00.000Z",
    sellerVerified: true,
    status: "active",
    visibility: "public",
  },
  {
    id: "l-vw-golf-1",
    title: "VW Golf 2012",
    price: 4500,
    location: "Klaipėda",
    category: "vehicles",
    brand: "Volkswagen",
    model: "Golf",
    year: 2012,
    mileage: 190000,
    fuel: "diesel",
    transmission: "manual",
    distanceKm: 45,
    createdAt: "2026-07-20T10:00:00.000Z",
    sellerVerified: false,
    status: "active",
    visibility: "public",
  },
  {
    id: "l-tesla-3-1",
    title: "Tesla Model 3 elektra",
    price: 24500,
    location: "Vilnius",
    category: "vehicles",
    brand: "Tesla",
    model: "Model 3",
    year: 2021,
    mileage: 40000,
    fuel: "electric",
    transmission: "automatic",
    distanceKm: 5,
    createdAt: "2026-08-05T10:00:00.000Z",
    sellerVerified: true,
    status: "active",
    visibility: "public",
  },
  {
    id: "l-opel-astra-1",
    title: "Opel Astra mechaninė",
    price: 1800,
    location: "Šiauliai",
    category: "vehicles",
    brand: "Opel",
    model: "Astra",
    year: 2008,
    mileage: 250000,
    fuel: "petrol",
    transmission: "manual",
    distanceKm: 120,
    createdAt: "2026-06-01T10:00:00.000Z",
    sellerVerified: false,
    status: "active",
    visibility: "public",
  },
  {
    id: "l-ford-focus-1",
    title: "Ford Focus 2011",
    price: 3200,
    location: "Kaunas",
    category: "vehicles",
    brand: "Ford",
    model: "Focus",
    year: 2011,
    mileage: 210000,
    fuel: "diesel",
    transmission: "manual",
    distanceKm: 15,
    createdAt: "2026-08-03T10:00:00.000Z",
    sellerVerified: true,
    status: "active",
    visibility: "public",
  },
  {
    id: "l-iphone-13-1",
    title: "iPhone 13 128GB",
    price: 480,
    location: "Vilnius",
    category: "electronics",
    brand: "iphone",
    model: "13",
    condition: "used",
    distanceKm: 3,
    createdAt: "2026-08-04T10:00:00.000Z",
    sellerVerified: true,
    status: "active",
    visibility: "public",
  },
  {
    id: "l-samsung-s22-1",
    title: "Samsung Galaxy S22",
    price: 350,
    location: "Kaunas",
    category: "electronics",
    brand: "samsung",
    model: "S22",
    condition: "used",
    distanceKm: 18,
    createdAt: "2026-08-01T12:00:00.000Z",
    sellerVerified: false,
    status: "active",
    visibility: "public",
  },
  {
    id: "l-xiaomi-1",
    title: "Xiaomi Redmi Note",
    price: 120,
    location: "Panevėžys",
    category: "electronics",
    brand: "xiaomi",
    condition: "used",
    distanceKm: 90,
    createdAt: "2026-07-15T10:00:00.000Z",
    sellerVerified: false,
    status: "active",
    visibility: "public",
  },
  {
    id: "l-pixel-7-1",
    title: "Google Pixel 7",
    price: 290,
    location: "Vilnius",
    category: "electronics",
    brand: "pixel",
    model: "7",
    condition: "used",
    distanceKm: 6,
    createdAt: "2026-08-06T10:00:00.000Z",
    sellerVerified: true,
    status: "active",
    visibility: "public",
  },
  {
    id: "l-sofa-1",
    title: "Sofa svetainei",
    price: 200,
    location: "Vilnius",
    category: "home",
    distanceKm: 4,
    createdAt: "2026-08-02T08:00:00.000Z",
    sellerVerified: false,
    status: "active",
    visibility: "public",
  },
  {
    id: "l-bike-1",
    title: "Dviratis trekking",
    price: 150,
    location: "Kaunas",
    category: "other",
    distanceKm: 20,
    createdAt: "2026-07-28T10:00:00.000Z",
    sellerVerified: false,
    status: "active",
    visibility: "public",
  },
  // Invisible / forbidden rows — must never appear in NL results
  {
    id: "l-banned-1",
    title: "BMW banned listing",
    price: 1000,
    location: "Vilnius",
    category: "vehicles",
    brand: "BMW",
    model: "e46",
    year: 2004,
    banned: true,
    status: "active",
    visibility: "public",
    createdAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "l-hidden-1",
    title: "Hidden Audi",
    price: 5000,
    location: "Kaunas",
    category: "vehicles",
    brand: "Audi",
    model: "A4",
    visibility: "hidden",
    status: "hidden",
    createdAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "l-private-1",
    title: "Private draft BMW",
    price: 3000,
    location: "Vilnius",
    category: "vehicles",
    brand: "BMW",
    visibility: "private",
    ownerUserId: "user-secret",
    createdAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "l-review-1",
    title: "Pending review Tesla",
    price: 20000,
    location: "Vilnius",
    category: "vehicles",
    brand: "Tesla",
    requiresReview: true,
    status: "active",
    visibility: "public",
    createdAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "l-sold-1",
    title: "Sold VW Golf",
    price: 4000,
    location: "Vilnius",
    category: "vehicles",
    brand: "Volkswagen",
    model: "Golf",
    status: "sold",
    visibility: "public",
    createdAt: "2026-08-01T10:00:00.000Z",
  },
];

export function fixtureCatalogPort() {
  return {
    loadCandidates: () => NL_SEARCH_FIXTURE_CATALOG,
  };
}
